package com.stel.gemmunch.ui.theme

import androidx.compose.ui.graphics.Color

// Custom Material 3 Color Palette for GemMunch
// Primary color: A vibrant green

// Light Theme Colors
val light_primary = Color(0xFF006E2C)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFF8CFA9F)
val light_onPrimaryContainer = Color(0xFF002108)
val light_secondary = Color(0xFF516350)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFD4E8D1)
val light_onSecondaryContainer = Color(0xFF0F1F11)
val light_tertiary = Color(0xFF39656C)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFBDEAF2)
val light_onTertiaryContainer = Color(0xFF001F24)
val light_error = Color(0xFFBA1A1A)
val light_onError = Color(0xFFFFFFFF)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFCFDF7)
val light_onBackground = Color(0xFF1A1C19)
val light_surface = Color(0xFFFCFDF7)
val light_onSurface = Color(0xFF1A1C19)
val light_surfaceVariant = Color(0xFFDDE5D9)
val light_onSurfaceVariant = Color(0xFF424940)
val light_outline = Color(0xFF727970)

// Dark Theme Colors
val dark_primary = Color(0xFF70DD85)
val dark_onPrimary = Color(0xFF003913)
val dark_primaryContainer = Color(0xFF005320)
val dark_onPrimaryContainer = Color(0xFF8CFA9F)
val dark_secondary = Color(0xFFB8CCB5)
val dark_onSecondary = Color(0xFF243424)
val dark_secondaryContainer = Color(0xFF3A4B3A)
val dark_onSecondaryContainer = Color(0xFFD4E8D1)
val dark_tertiary = Color(0xFFA1CED6)
val dark_onTertiary = Color(0xFF00363D)
val dark_tertiaryContainer = Color(0xFF1F4D54)
val dark_onTertiaryContainer = Color(0xFFBDEAF2)
val dark_error = Color(0xFFFFB4AB)
val dark_onError = Color(0xFF690005)
val dark_errorContainer = Color(0xFF93000A)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF1A1C19)
val dark_onBackground = Color(0xFFE2E3DE)
val dark_surface = Color(0xFF1A1C19)
val dark_onSurface = Color(0xFFE2E3DE)
val dark_surfaceVariant = Color(0xFF424940)
val dark_onSurfaceVariant = Color(0xFFC2C9BE)
val dark_outline = Color(0xFF8B9389)