"""
Common foods nutritional data with comprehensive nutrient profiles
"""

COMMON_FOODS_DATA = [
    # Fruits
    {
        "name": "Apple (medium)",
        "serving_size": "1 medium (182g)",
        "serving_size_grams": 182,
        "calories": 95,
        "total_fat_g": 0.3,
        "saturated_fat_g": 0.1,
        "cholesterol_mg": 0,
        "sodium_mg": 2,
        "total_carbohydrate_g": 25,
        "dietary_fiber_g": 4.4,
        "sugars_g": 19,
        "protein_g": 0.5,
        "vitamin_c_mg": 8.4,
        "potassium_mg": 195,
        "vitamin_a_mcg_rae": 5,
        "calcium_mg": 11,
        "iron_mg": 0.2,
        "glycemic_index": 36,
        "category": "Fruits",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Banana (medium)",
        "serving_size": "1 medium (118g)",
        "serving_size_grams": 118,
        "calories": 105,
        "total_fat_g": 0.4,
        "saturated_fat_g": 0.1,
        "cholesterol_mg": 0,
        "sodium_mg": 1,
        "total_carbohydrate_g": 27,
        "dietary_fiber_g": 3.1,
        "sugars_g": 14,
        "protein_g": 1.3,
        "vitamin_c_mg": 10.3,
        "vitamin_b6_mg": 0.4,
        "potassium_mg": 422,
        "magnesium_mg": 32,
        "glycemic_index": 51,
        "category": "Fruits",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Orange (medium)",
        "serving_size": "1 medium (154g)",
        "serving_size_grams": 154,
        "calories": 62,
        "total_fat_g": 0.2,
        "saturated_fat_g": 0,
        "cholesterol_mg": 0,
        "sodium_mg": 0,
        "total_carbohydrate_g": 15,
        "dietary_fiber_g": 3.1,
        "sugars_g": 12,
        "protein_g": 1.2,
        "vitamin_c_mg": 70,
        "folate_mcg": 40,
        "potassium_mg": 237,
        "calcium_mg": 52,
        "glycemic_index": 43,
        "category": "Fruits",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Strawberries",
        "serving_size": "1 cup (152g)",
        "serving_size_grams": 152,
        "calories": 49,
        "total_fat_g": 0.5,
        "saturated_fat_g": 0,
        "cholesterol_mg": 0,
        "sodium_mg": 2,
        "total_carbohydrate_g": 12,
        "dietary_fiber_g": 3,
        "sugars_g": 7,
        "protein_g": 1,
        "vitamin_c_mg": 89,
        "folate_mcg": 36,
        "potassium_mg": 233,
        "magnesium_mg": 20,
        "glycemic_index": 40,
        "category": "Fruits",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Blueberries",
        "serving_size": "1 cup (148g)",
        "serving_size_grams": 148,
        "calories": 84,
        "total_fat_g": 0.5,
        "saturated_fat_g": 0,
        "cholesterol_mg": 0,
        "sodium_mg": 1,
        "total_carbohydrate_g": 21,
        "dietary_fiber_g": 3.6,
        "sugars_g": 15,
        "protein_g": 1.1,
        "vitamin_c_mg": 14,
        "vitamin_k_mcg": 29,
        "potassium_mg": 114,
        "glycemic_index": 53,
        "category": "Fruits",
        "data_source": "Common Foods Database"
    },
    
    # Vegetables
    {
        "name": "Broccoli (cooked)",
        "serving_size": "1 cup (156g)",
        "serving_size_grams": 156,
        "calories": 55,
        "total_fat_g": 0.6,
        "saturated_fat_g": 0.1,
        "cholesterol_mg": 0,
        "sodium_mg": 64,
        "total_carbohydrate_g": 11,
        "dietary_fiber_g": 5.1,
        "sugars_g": 2.2,
        "protein_g": 3.7,
        "vitamin_c_mg": 101,
        "vitamin_k_mcg": 220,
        "vitamin_a_mcg_rae": 120,
        "calcium_mg": 62,
        "iron_mg": 1,
        "folate_mcg": 168,
        "glycemic_index": 15,
        "category": "Vegetables",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Spinach (raw)",
        "serving_size": "1 cup (30g)",
        "serving_size_grams": 30,
        "calories": 7,
        "total_fat_g": 0.1,
        "saturated_fat_g": 0,
        "cholesterol_mg": 0,
        "sodium_mg": 24,
        "total_carbohydrate_g": 1.1,
        "dietary_fiber_g": 0.7,
        "sugars_g": 0.1,
        "protein_g": 0.9,
        "vitamin_k_mcg": 145,
        "vitamin_a_mcg_rae": 141,
        "folate_mcg": 58,
        "iron_mg": 0.8,
        "calcium_mg": 30,
        "magnesium_mg": 24,
        "glycemic_index": 15,
        "category": "Vegetables",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Carrots (raw)",
        "serving_size": "1 cup (128g)",
        "serving_size_grams": 128,
        "calories": 52,
        "total_fat_g": 0.3,
        "saturated_fat_g": 0,
        "cholesterol_mg": 0,
        "sodium_mg": 88,
        "total_carbohydrate_g": 12,
        "dietary_fiber_g": 3.6,
        "sugars_g": 6.1,
        "protein_g": 1.2,
        "vitamin_a_mcg_rae": 1069,
        "vitamin_k_mcg": 17,
        "potassium_mg": 410,
        "vitamin_c_mg": 7.6,
        "glycemic_index": 35,
        "category": "Vegetables",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Tomato (medium)",
        "serving_size": "1 medium (123g)",
        "serving_size_grams": 123,
        "calories": 22,
        "total_fat_g": 0.2,
        "saturated_fat_g": 0,
        "cholesterol_mg": 0,
        "sodium_mg": 6,
        "total_carbohydrate_g": 4.8,
        "dietary_fiber_g": 1.5,
        "sugars_g": 3.2,
        "protein_g": 1.1,
        "vitamin_c_mg": 17,
        "vitamin_a_mcg_rae": 51,
        "vitamin_k_mcg": 10,
        "potassium_mg": 292,
        "glycemic_index": 15,
        "category": "Vegetables",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Sweet Potato (baked)",
        "serving_size": "1 medium (114g)",
        "serving_size_grams": 114,
        "calories": 103,
        "total_fat_g": 0.2,
        "saturated_fat_g": 0,
        "cholesterol_mg": 0,
        "sodium_mg": 41,
        "total_carbohydrate_g": 24,
        "dietary_fiber_g": 3.8,
        "sugars_g": 7.4,
        "protein_g": 2.3,
        "vitamin_a_mcg_rae": 1096,
        "vitamin_c_mg": 22,
        "potassium_mg": 542,
        "magnesium_mg": 31,
        "glycemic_index": 54,
        "category": "Vegetables",
        "data_source": "Common Foods Database"
    },
    
    # Grains
    {
        "name": "Brown Rice (cooked)",
        "serving_size": "1 cup (195g)",
        "serving_size_grams": 195,
        "calories": 218,
        "total_fat_g": 1.6,
        "saturated_fat_g": 0.3,
        "cholesterol_mg": 0,
        "sodium_mg": 2,
        "total_carbohydrate_g": 46,
        "dietary_fiber_g": 3.5,
        "sugars_g": 0.7,
        "protein_g": 4.5,
        "magnesium_mg": 86,
        "phosphorus_mg": 150,
        "manganese_mg": 1.8,
        "selenium_mcg": 19,
        "glycemic_index": 50,
        "category": "Grains",
        "data_source": "Common Foods Database"
    },
    {
        "name": "White Rice (cooked)",
        "serving_size": "1 cup (158g)",
        "serving_size_grams": 158,
        "calories": 205,
        "total_fat_g": 0.4,
        "saturated_fat_g": 0.1,
        "cholesterol_mg": 0,
        "sodium_mg": 2,
        "total_carbohydrate_g": 45,
        "dietary_fiber_g": 0.6,
        "sugars_g": 0.1,
        "protein_g": 4.3,
        "iron_mg": 1.9,
        "folate_mcg": 153,
        "niacin_mg": 2.3,
        "glycemic_index": 73,
        "category": "Grains",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Whole Wheat Bread",
        "serving_size": "1 slice (32g)",
        "serving_size_grams": 32,
        "calories": 81,
        "total_fat_g": 1.1,
        "saturated_fat_g": 0.2,
        "cholesterol_mg": 0,
        "sodium_mg": 146,
        "total_carbohydrate_g": 14,
        "dietary_fiber_g": 1.9,
        "sugars_g": 1.4,
        "protein_g": 4,
        "iron_mg": 0.9,
        "magnesium_mg": 24,
        "selenium_mcg": 12,
        "glycemic_index": 51,
        "category": "Grains",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Oatmeal (cooked)",
        "serving_size": "1 cup (234g)",
        "serving_size_grams": 234,
        "calories": 158,
        "total_fat_g": 3.2,
        "saturated_fat_g": 0.6,
        "cholesterol_mg": 0,
        "sodium_mg": 115,
        "total_carbohydrate_g": 27,
        "dietary_fiber_g": 4,
        "sugars_g": 1.1,
        "protein_g": 6,
        "iron_mg": 2.1,
        "magnesium_mg": 63,
        "phosphorus_mg": 180,
        "zinc_mg": 2.3,
        "glycemic_index": 55,
        "category": "Grains",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Quinoa (cooked)",
        "serving_size": "1 cup (185g)",
        "serving_size_grams": 185,
        "calories": 222,
        "total_fat_g": 3.6,
        "saturated_fat_g": 0.4,
        "cholesterol_mg": 0,
        "sodium_mg": 13,
        "total_carbohydrate_g": 39,
        "dietary_fiber_g": 5.2,
        "sugars_g": 1.6,
        "protein_g": 8.1,
        "iron_mg": 2.8,
        "magnesium_mg": 118,
        "phosphorus_mg": 281,
        "folate_mcg": 78,
        "glycemic_index": 53,
        "category": "Grains",
        "data_source": "Common Foods Database"
    },
    
    # Protein Sources
    {
        "name": "Chicken Breast (grilled)",
        "serving_size": "3 oz (85g)",
        "serving_size_grams": 85,
        "calories": 128,
        "total_fat_g": 2.7,
        "saturated_fat_g": 0.7,
        "cholesterol_mg": 88,
        "sodium_mg": 44,
        "total_carbohydrate_g": 0,
        "dietary_fiber_g": 0,
        "sugars_g": 0,
        "protein_g": 26,
        "niacin_mg": 11.8,
        "vitamin_b6_mg": 0.9,
        "phosphorus_mg": 230,
        "selenium_mcg": 30,
        "glycemic_index": 0,
        "category": "Meat",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Salmon (Atlantic, cooked)",
        "serving_size": "3 oz (85g)",
        "serving_size_grams": 85,
        "calories": 175,
        "total_fat_g": 10.5,
        "saturated_fat_g": 2.1,
        "cholesterol_mg": 54,
        "sodium_mg": 52,
        "total_carbohydrate_g": 0,
        "dietary_fiber_g": 0,
        "sugars_g": 0,
        "protein_g": 19,
        "vitamin_d_mcg": 11,
        "vitamin_b12_mcg": 2.6,
        "selenium_mcg": 40,
        "omega3_fatty_acids_mg": 1800,
        "glycemic_index": 0,
        "category": "Fish",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Egg (large, whole)",
        "serving_size": "1 large (50g)",
        "serving_size_grams": 50,
        "calories": 72,
        "total_fat_g": 4.8,
        "saturated_fat_g": 1.6,
        "cholesterol_mg": 186,
        "sodium_mg": 71,
        "total_carbohydrate_g": 0.4,
        "dietary_fiber_g": 0,
        "sugars_g": 0.2,
        "protein_g": 6.3,
        "vitamin_d_mcg": 1,
        "vitamin_b12_mcg": 0.5,
        "choline_mg": 147,
        "selenium_mcg": 15,
        "glycemic_index": 0,
        "category": "Eggs",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Tofu (firm)",
        "serving_size": "1/2 cup (126g)",
        "serving_size_grams": 126,
        "calories": 181,
        "total_fat_g": 11,
        "saturated_fat_g": 1.6,
        "cholesterol_mg": 0,
        "sodium_mg": 18,
        "total_carbohydrate_g": 3.5,
        "dietary_fiber_g": 2.9,
        "sugars_g": 0.7,
        "protein_g": 22,
        "calcium_mg": 861,
        "iron_mg": 3.4,
        "magnesium_mg": 73,
        "glycemic_index": 15,
        "category": "Plant Protein",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Black Beans (cooked)",
        "serving_size": "1 cup (172g)",
        "serving_size_grams": 172,
        "calories": 227,
        "total_fat_g": 0.9,
        "saturated_fat_g": 0.2,
        "cholesterol_mg": 0,
        "sodium_mg": 2,
        "total_carbohydrate_g": 41,
        "dietary_fiber_g": 15,
        "sugars_g": 0.6,
        "protein_g": 15,
        "folate_mcg": 256,
        "iron_mg": 3.6,
        "magnesium_mg": 120,
        "potassium_mg": 611,
        "glycemic_index": 30,
        "category": "Legumes",
        "data_source": "Common Foods Database"
    },
    
    # Dairy
    {
        "name": "Milk (2%)",
        "serving_size": "1 cup (244g)",
        "serving_size_grams": 244,
        "calories": 122,
        "total_fat_g": 4.8,
        "saturated_fat_g": 3.1,
        "cholesterol_mg": 20,
        "sodium_mg": 115,
        "total_carbohydrate_g": 12,
        "dietary_fiber_g": 0,
        "sugars_g": 12,
        "protein_g": 8.1,
        "calcium_mg": 293,
        "vitamin_d_mcg": 2.9,
        "vitamin_b12_mcg": 1.3,
        "phosphorus_mg": 224,
        "glycemic_index": 37,
        "category": "Dairy",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Greek Yogurt (plain, nonfat)",
        "serving_size": "1 cup (245g)",
        "serving_size_grams": 245,
        "calories": 133,
        "total_fat_g": 0.9,
        "saturated_fat_g": 0.3,
        "cholesterol_mg": 10,
        "sodium_mg": 92,
        "total_carbohydrate_g": 9,
        "dietary_fiber_g": 0,
        "sugars_g": 9,
        "protein_g": 23,
        "calcium_mg": 250,
        "vitamin_b12_mcg": 1.5,
        "phosphorus_mg": 240,
        "glycemic_index": 35,
        "category": "Dairy",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Cheddar Cheese",
        "serving_size": "1 oz (28g)",
        "serving_size_grams": 28,
        "calories": 114,
        "total_fat_g": 9.4,
        "saturated_fat_g": 6,
        "cholesterol_mg": 30,
        "sodium_mg": 176,
        "total_carbohydrate_g": 0.4,
        "dietary_fiber_g": 0,
        "sugars_g": 0.1,
        "protein_g": 7,
        "calcium_mg": 204,
        "vitamin_a_mcg_rae": 75,
        "phosphorus_mg": 145,
        "glycemic_index": 0,
        "category": "Dairy",
        "data_source": "Common Foods Database"
    },
    
    # Nuts and Seeds
    {
        "name": "Almonds",
        "serving_size": "1 oz (28g)",
        "serving_size_grams": 28,
        "calories": 164,
        "total_fat_g": 14.2,
        "saturated_fat_g": 1.1,
        "cholesterol_mg": 0,
        "sodium_mg": 0,
        "total_carbohydrate_g": 6.1,
        "dietary_fiber_g": 3.5,
        "sugars_g": 1.2,
        "protein_g": 6,
        "vitamin_e_mg": 7.3,
        "magnesium_mg": 76,
        "calcium_mg": 76,
        "iron_mg": 1,
        "glycemic_index": 15,
        "category": "Nuts",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Walnuts",
        "serving_size": "1 oz (28g)",
        "serving_size_grams": 28,
        "calories": 185,
        "total_fat_g": 18.5,
        "saturated_fat_g": 1.7,
        "cholesterol_mg": 0,
        "sodium_mg": 1,
        "total_carbohydrate_g": 3.9,
        "dietary_fiber_g": 1.9,
        "sugars_g": 0.7,
        "protein_g": 4.3,
        "omega3_fatty_acids_mg": 2570,
        "magnesium_mg": 45,
        "phosphorus_mg": 98,
        "glycemic_index": 15,
        "category": "Nuts",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Chia Seeds",
        "serving_size": "1 oz (28g)",
        "serving_size_grams": 28,
        "calories": 138,
        "total_fat_g": 8.7,
        "saturated_fat_g": 0.9,
        "cholesterol_mg": 0,
        "sodium_mg": 5,
        "total_carbohydrate_g": 12,
        "dietary_fiber_g": 9.8,
        "sugars_g": 0,
        "protein_g": 4.7,
        "calcium_mg": 179,
        "omega3_fatty_acids_mg": 5060,
        "phosphorus_mg": 265,
        "magnesium_mg": 95,
        "glycemic_index": 1,
        "category": "Seeds",
        "data_source": "Common Foods Database"
    },
    
    # Common Prepared Foods
    {
        "name": "Pasta with Marinara Sauce",
        "serving_size": "1 cup (250g)",
        "serving_size_grams": 250,
        "calories": 185,
        "total_fat_g": 3.2,
        "saturated_fat_g": 0.5,
        "cholesterol_mg": 0,
        "sodium_mg": 435,
        "total_carbohydrate_g": 35,
        "dietary_fiber_g": 3.5,
        "sugars_g": 7,
        "protein_g": 6,
        "vitamin_c_mg": 12,
        "iron_mg": 2.1,
        "glycemic_index": 50,
        "category": "Prepared Foods",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Pepperoni Pizza (1 slice)",
        "serving_size": "1 slice (107g)",
        "serving_size_grams": 107,
        "calories": 298,
        "total_fat_g": 12,
        "saturated_fat_g": 5.1,
        "cholesterol_mg": 25,
        "sodium_mg": 683,
        "total_carbohydrate_g": 34,
        "dietary_fiber_g": 2.5,
        "sugars_g": 3.8,
        "protein_g": 13,
        "calcium_mg": 184,
        "iron_mg": 2.5,
        "glycemic_index": 60,
        "category": "Prepared Foods",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Grilled Cheese Sandwich",
        "serving_size": "1 sandwich (119g)",
        "serving_size_grams": 119,
        "calories": 366,
        "total_fat_g": 23,
        "saturated_fat_g": 13,
        "cholesterol_mg": 60,
        "sodium_mg": 855,
        "total_carbohydrate_g": 28,
        "dietary_fiber_g": 1.2,
        "sugars_g": 3.4,
        "protein_g": 13,
        "calcium_mg": 391,
        "vitamin_a_mcg_rae": 195,
        "glycemic_index": 55,
        "category": "Prepared Foods",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Caesar Salad (with dressing)",
        "serving_size": "1.5 cups (206g)",
        "serving_size_grams": 206,
        "calories": 184,
        "total_fat_g": 16,
        "saturated_fat_g": 3.6,
        "cholesterol_mg": 17,
        "sodium_mg": 409,
        "total_carbohydrate_g": 7.3,
        "dietary_fiber_g": 2.3,
        "sugars_g": 1.5,
        "protein_g": 4.2,
        "vitamin_a_mcg_rae": 302,
        "vitamin_k_mcg": 109,
        "calcium_mg": 118,
        "glycemic_index": 10,
        "category": "Salads",
        "data_source": "Common Foods Database"
    },
    
    # Beverages
    {
        "name": "Orange Juice",
        "serving_size": "1 cup (248g)",
        "serving_size_grams": 248,
        "calories": 112,
        "total_fat_g": 0.5,
        "saturated_fat_g": 0.1,
        "cholesterol_mg": 0,
        "sodium_mg": 2,
        "total_carbohydrate_g": 26,
        "dietary_fiber_g": 0.5,
        "sugars_g": 21,
        "protein_g": 1.7,
        "vitamin_c_mg": 124,
        "folate_mcg": 74,
        "potassium_mg": 496,
        "glycemic_index": 50,
        "category": "Beverages",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Coffee (black)",
        "serving_size": "1 cup (237g)",
        "serving_size_grams": 237,
        "calories": 2,
        "total_fat_g": 0,
        "saturated_fat_g": 0,
        "cholesterol_mg": 0,
        "sodium_mg": 5,
        "total_carbohydrate_g": 0,
        "dietary_fiber_g": 0,
        "sugars_g": 0,
        "protein_g": 0.3,
        "caffeine_mg": 95,
        "potassium_mg": 116,
        "magnesium_mg": 7,
        "glycemic_index": 0,
        "category": "Beverages",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Cola (regular)",
        "serving_size": "12 fl oz (355g)",
        "serving_size_grams": 355,
        "calories": 140,
        "total_fat_g": 0,
        "saturated_fat_g": 0,
        "cholesterol_mg": 0,
        "sodium_mg": 45,
        "total_carbohydrate_g": 39,
        "dietary_fiber_g": 0,
        "sugars_g": 39,
        "protein_g": 0,
        "caffeine_mg": 34,
        "phosphorus_mg": 41,
        "glycemic_index": 63,
        "category": "Beverages",
        "data_source": "Common Foods Database"
    },
    
    # Snacks
    {
        "name": "Potato Chips",
        "serving_size": "1 oz (28g)",
        "serving_size_grams": 28,
        "calories": 152,
        "total_fat_g": 10,
        "saturated_fat_g": 3.1,
        "cholesterol_mg": 0,
        "sodium_mg": 148,
        "total_carbohydrate_g": 15,
        "dietary_fiber_g": 1.4,
        "sugars_g": 0.1,
        "protein_g": 2,
        "potassium_mg": 342,
        "vitamin_c_mg": 7.8,
        "glycemic_index": 56,
        "category": "Snacks",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Chocolate Chip Cookie",
        "serving_size": "1 medium (16g)",
        "serving_size_grams": 16,
        "calories": 78,
        "total_fat_g": 3.6,
        "saturated_fat_g": 1.2,
        "cholesterol_mg": 5,
        "sodium_mg": 55,
        "total_carbohydrate_g": 11,
        "dietary_fiber_g": 0.3,
        "sugars_g": 5.5,
        "protein_g": 0.9,
        "calcium_mg": 7,
        "iron_mg": 0.4,
        "glycemic_index": 62,
        "category": "Snacks",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Popcorn (air-popped)",
        "serving_size": "3 cups (24g)",
        "serving_size_grams": 24,
        "calories": 93,
        "total_fat_g": 1.1,
        "saturated_fat_g": 0.2,
        "cholesterol_mg": 0,
        "sodium_mg": 2,
        "total_carbohydrate_g": 19,
        "dietary_fiber_g": 3.5,
        "sugars_g": 0.2,
        "protein_g": 3,
        "magnesium_mg": 34,
        "phosphorus_mg": 86,
        "glycemic_index": 65,
        "category": "Snacks",
        "data_source": "Common Foods Database"
    }
]