"""
Expanded common foods nutritional data for demo purposes
Includes visual foods commonly photographed and popular packaged items
"""

EXPANDED_COMMON_FOODS = [
    # ========== FRUITS (Commonly Photographed) ==========
    {
        "name": "Strawberries",
        "serving_size": "1 cup (152g)",
        "serving_size_grams": 152,
        "calories": 49,
        "total_fat_g": 0.5,
        "saturated_fat_g": 0.0,
        "cholesterol_mg": 0,
        "sodium_mg": 2,
        "total_carbohydrate_g": 12,
        "dietary_fiber_g": 3,
        "sugars_g": 7,
        "protein_g": 1,
        "vitamin_c_mg": 89.4,
        "folate_mcg": 36,
        "potassium_mg": 233,
        "manganese_mg": 0.6,
        "glycemic_index": 40,
        "category": "Fruits",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Watermelon",
        "serving_size": "1 cup diced (152g)",
        "serving_size_grams": 152,
        "calories": 46,
        "total_fat_g": 0.2,
        "saturated_fat_g": 0.0,
        "cholesterol_mg": 0,
        "sodium_mg": 2,
        "total_carbohydrate_g": 11.5,
        "dietary_fiber_g": 0.6,
        "sugars_g": 9.4,
        "protein_g": 0.9,
        "vitamin_c_mg": 12.3,
        "vitamin_a_mcg_rae": 43,
        "lycopene_mg": 6.9,
        "potassium_mg": 170,
        "glycemic_index": 72,
        "category": "Fruits",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Grapes (red or green)",
        "serving_size": "1 cup (151g)",
        "serving_size_grams": 151,
        "calories": 104,
        "total_fat_g": 0.2,
        "saturated_fat_g": 0.1,
        "cholesterol_mg": 0,
        "sodium_mg": 3,
        "total_carbohydrate_g": 27.3,
        "dietary_fiber_g": 1.4,
        "sugars_g": 23.4,
        "protein_g": 1.1,
        "vitamin_c_mg": 16.3,
        "vitamin_k_mcg": 22,
        "potassium_mg": 288,
        "glycemic_index": 59,
        "category": "Fruits",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Pineapple",
        "serving_size": "1 cup chunks (165g)",
        "serving_size_grams": 165,
        "calories": 82,
        "total_fat_g": 0.2,
        "saturated_fat_g": 0.0,
        "cholesterol_mg": 0,
        "sodium_mg": 2,
        "total_carbohydrate_g": 21.6,
        "dietary_fiber_g": 2.3,
        "sugars_g": 16.3,
        "protein_g": 0.9,
        "vitamin_c_mg": 78.9,
        "manganese_mg": 1.5,
        "thiamin_mg": 0.1,
        "glycemic_index": 59,
        "category": "Fruits",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Mango",
        "serving_size": "1 cup sliced (165g)",
        "serving_size_grams": 165,
        "calories": 99,
        "total_fat_g": 0.6,
        "saturated_fat_g": 0.1,
        "cholesterol_mg": 0,
        "sodium_mg": 2,
        "total_carbohydrate_g": 24.7,
        "dietary_fiber_g": 2.6,
        "sugars_g": 22.5,
        "protein_g": 1.4,
        "vitamin_c_mg": 60.1,
        "vitamin_a_mcg_rae": 89,
        "folate_mcg": 71,
        "vitamin_e_mg": 1.5,
        "glycemic_index": 51,
        "category": "Fruits",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Avocado",
        "serving_size": "1/2 avocado (68g)",
        "serving_size_grams": 68,
        "calories": 114,
        "total_fat_g": 10.5,
        "saturated_fat_g": 1.5,
        "monounsaturated_fat_g": 7.0,
        "polyunsaturated_fat_g": 1.3,
        "cholesterol_mg": 0,
        "sodium_mg": 5,
        "total_carbohydrate_g": 6,
        "dietary_fiber_g": 4.6,
        "sugars_g": 0.5,
        "protein_g": 1.3,
        "vitamin_k_mcg": 14,
        "folate_mcg": 59,
        "vitamin_c_mg": 6,
        "potassium_mg": 345,
        "glycemic_index": 15,
        "category": "Fruits",
        "data_source": "Common Foods Database"
    },
    
    # ========== VEGETABLES (Commonly Photographed) ==========
    {
        "name": "Broccoli (raw)",
        "serving_size": "1 cup chopped (91g)",
        "serving_size_grams": 91,
        "calories": 31,
        "total_fat_g": 0.3,
        "saturated_fat_g": 0.0,
        "cholesterol_mg": 0,
        "sodium_mg": 30,
        "total_carbohydrate_g": 6,
        "dietary_fiber_g": 2.4,
        "sugars_g": 1.5,
        "protein_g": 2.5,
        "vitamin_c_mg": 81.2,
        "vitamin_k_mcg": 92.5,
        "folate_mcg": 57,
        "potassium_mg": 288,
        "glycemic_index": 15,
        "category": "Vegetables",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Bell Pepper (red)",
        "serving_size": "1 medium (119g)",
        "serving_size_grams": 119,
        "calories": 37,
        "total_fat_g": 0.4,
        "saturated_fat_g": 0.0,
        "cholesterol_mg": 0,
        "sodium_mg": 5,
        "total_carbohydrate_g": 7.2,
        "dietary_fiber_g": 2.5,
        "sugars_g": 5,
        "protein_g": 1.2,
        "vitamin_c_mg": 152,
        "vitamin_a_mcg_rae": 187,
        "vitamin_b6_mg": 0.3,
        "folate_mcg": 55,
        "glycemic_index": 15,
        "category": "Vegetables",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Cucumber",
        "serving_size": "1 cup sliced (104g)",
        "serving_size_grams": 104,
        "calories": 16,
        "total_fat_g": 0.1,
        "saturated_fat_g": 0.0,
        "cholesterol_mg": 0,
        "sodium_mg": 2,
        "total_carbohydrate_g": 3.8,
        "dietary_fiber_g": 0.5,
        "sugars_g": 1.7,
        "protein_g": 0.7,
        "vitamin_k_mcg": 17,
        "potassium_mg": 152,
        "magnesium_mg": 14,
        "glycemic_index": 15,
        "category": "Vegetables",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Kale (raw)",
        "serving_size": "1 cup (67g)",
        "serving_size_grams": 67,
        "calories": 33,
        "total_fat_g": 0.6,
        "saturated_fat_g": 0.1,
        "cholesterol_mg": 0,
        "sodium_mg": 29,
        "total_carbohydrate_g": 6,
        "dietary_fiber_g": 2.6,
        "sugars_g": 1.3,
        "protein_g": 2.9,
        "vitamin_a_mcg_rae": 378,
        "vitamin_c_mg": 80.4,
        "vitamin_k_mcg": 547,
        "calcium_mg": 90,
        "iron_mg": 1,
        "glycemic_index": 15,
        "category": "Vegetables",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Cauliflower (raw)",
        "serving_size": "1 cup (107g)",
        "serving_size_grams": 107,
        "calories": 27,
        "total_fat_g": 0.3,
        "saturated_fat_g": 0.1,
        "cholesterol_mg": 0,
        "sodium_mg": 32,
        "total_carbohydrate_g": 5.3,
        "dietary_fiber_g": 2.1,
        "sugars_g": 2,
        "protein_g": 2.1,
        "vitamin_c_mg": 51.6,
        "vitamin_k_mcg": 16.6,
        "folate_mcg": 61,
        "choline_mg": 47.4,
        "glycemic_index": 15,
        "category": "Vegetables",
        "data_source": "Common Foods Database"
    },
    
    # ========== PROTEINS (Commonly Photographed) ==========
    {
        "name": "Eggs (scrambled)",
        "serving_size": "2 large eggs",
        "serving_size_grams": 122,
        "calories": 182,
        "total_fat_g": 13.3,
        "saturated_fat_g": 4.1,
        "cholesterol_mg": 429,
        "sodium_mg": 171,
        "total_carbohydrate_g": 1.9,
        "dietary_fiber_g": 0,
        "sugars_g": 1.5,
        "protein_g": 12.6,
        "vitamin_d_mcg": 2.2,
        "vitamin_b12_mcg": 1.1,
        "selenium_mcg": 27.4,
        "choline_mg": 294,
        "glycemic_index": 0,
        "category": "Proteins",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Bacon (cooked)",
        "serving_size": "3 slices (24g)",
        "serving_size_grams": 24,
        "calories": 123,
        "total_fat_g": 9.5,
        "saturated_fat_g": 3.2,
        "cholesterol_mg": 24,
        "sodium_mg": 452,
        "total_carbohydrate_g": 0.4,
        "dietary_fiber_g": 0,
        "sugars_g": 0,
        "protein_g": 8.9,
        "selenium_mcg": 13.4,
        "phosphorus_mg": 134,
        "glycemic_index": 0,
        "category": "Proteins",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Steak (sirloin, grilled)",
        "serving_size": "3 oz (85g)",
        "serving_size_grams": 85,
        "calories": 207,
        "total_fat_g": 12.7,
        "saturated_fat_g": 5.1,
        "cholesterol_mg": 55,
        "sodium_mg": 54,
        "total_carbohydrate_g": 0,
        "dietary_fiber_g": 0,
        "sugars_g": 0,
        "protein_g": 22.8,
        "iron_mg": 2.6,
        "zinc_mg": 4.5,
        "vitamin_b12_mcg": 1.5,
        "selenium_mcg": 26.2,
        "glycemic_index": 0,
        "category": "Proteins",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Tofu (firm)",
        "serving_size": "1/2 cup (126g)",
        "serving_size_grams": 126,
        "calories": 94,
        "total_fat_g": 6,
        "saturated_fat_g": 0.9,
        "cholesterol_mg": 0,
        "sodium_mg": 9,
        "total_carbohydrate_g": 2.3,
        "dietary_fiber_g": 0.5,
        "sugars_g": 0.7,
        "protein_g": 10,
        "calcium_mg": 227,
        "iron_mg": 1.6,
        "magnesium_mg": 37,
        "glycemic_index": 15,
        "category": "Proteins",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Shrimp (cooked)",
        "serving_size": "3 oz (85g)",
        "serving_size_grams": 85,
        "calories": 84,
        "total_fat_g": 0.9,
        "saturated_fat_g": 0.2,
        "cholesterol_mg": 161,
        "sodium_mg": 805,
        "total_carbohydrate_g": 0,
        "dietary_fiber_g": 0,
        "sugars_g": 0,
        "protein_g": 20.4,
        "selenium_mcg": 34,
        "vitamin_b12_mcg": 1.4,
        "phosphorus_mg": 201,
        "glycemic_index": 0,
        "category": "Proteins",
        "data_source": "Common Foods Database"
    },
    
    # ========== GRAINS & PASTA (Commonly Photographed) ==========
    {
        "name": "Pasta (spaghetti, cooked)",
        "serving_size": "1 cup (140g)",
        "serving_size_grams": 140,
        "calories": 220,
        "total_fat_g": 1.3,
        "saturated_fat_g": 0.2,
        "cholesterol_mg": 0,
        "sodium_mg": 1,
        "total_carbohydrate_g": 43,
        "dietary_fiber_g": 2.5,
        "sugars_g": 0.8,
        "protein_g": 8.1,
        "iron_mg": 1.8,
        "folate_mcg": 102,
        "manganese_mg": 0.9,
        "selenium_mcg": 36.6,
        "glycemic_index": 49,
        "category": "Grains",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Quinoa (cooked)",
        "serving_size": "1 cup (185g)",
        "serving_size_grams": 185,
        "calories": 222,
        "total_fat_g": 3.6,
        "saturated_fat_g": 0.4,
        "cholesterol_mg": 0,
        "sodium_mg": 13,
        "total_carbohydrate_g": 39.4,
        "dietary_fiber_g": 5.2,
        "sugars_g": 1.6,
        "protein_g": 8.1,
        "iron_mg": 2.8,
        "magnesium_mg": 118,
        "phosphorus_mg": 281,
        "folate_mcg": 78,
        "glycemic_index": 53,
        "category": "Grains",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Oatmeal (cooked)",
        "serving_size": "1 cup (234g)",
        "serving_size_grams": 234,
        "calories": 158,
        "total_fat_g": 3.2,
        "saturated_fat_g": 0.6,
        "cholesterol_mg": 0,
        "sodium_mg": 115,
        "total_carbohydrate_g": 27.4,
        "dietary_fiber_g": 4,
        "sugars_g": 1.1,
        "protein_g": 5.5,
        "iron_mg": 2.1,
        "magnesium_mg": 61,
        "phosphorus_mg": 180,
        "glycemic_index": 55,
        "category": "Grains",
        "data_source": "Common Foods Database"
    },
    
    # ========== POPULAR SNACKS & PACKAGED FOODS ==========
    {
        "name": "Oreos",
        "brand_name": "Nabisco",
        "serving_size": "3 cookies (34g)",
        "serving_size_grams": 34,
        "calories": 160,
        "total_fat_g": 7,
        "saturated_fat_g": 2,
        "trans_fat_g": 0,
        "cholesterol_mg": 0,
        "sodium_mg": 135,
        "total_carbohydrate_g": 25,
        "dietary_fiber_g": 1,
        "sugars_g": 14,
        "protein_g": 1,
        "iron_mg": 1.4,
        "category": "Snacks",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Doritos Nacho Cheese",
        "brand_name": "Frito-Lay",
        "serving_size": "1 oz (28g)",
        "serving_size_grams": 28,
        "calories": 150,
        "total_fat_g": 8,
        "saturated_fat_g": 1,
        "trans_fat_g": 0,
        "cholesterol_mg": 0,
        "sodium_mg": 210,
        "total_carbohydrate_g": 18,
        "dietary_fiber_g": 1,
        "sugars_g": 1,
        "protein_g": 2,
        "category": "Snacks",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Cheerios",
        "brand_name": "General Mills",
        "serving_size": "1 cup (28g)",
        "serving_size_grams": 28,
        "calories": 100,
        "total_fat_g": 2,
        "saturated_fat_g": 0,
        "cholesterol_mg": 0,
        "sodium_mg": 140,
        "total_carbohydrate_g": 20,
        "dietary_fiber_g": 3,
        "sugars_g": 1,
        "protein_g": 3,
        "iron_mg": 10.8,
        "vitamin_c_mg": 10,
        "vitamin_d_mcg": 2,
        "calcium_mg": 100,
        "category": "Breakfast",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Coca-Cola Classic",
        "brand_name": "Coca-Cola",
        "serving_size": "12 fl oz (355ml)",
        "serving_size_grams": 355,
        "calories": 140,
        "total_fat_g": 0,
        "saturated_fat_g": 0,
        "cholesterol_mg": 0,
        "sodium_mg": 45,
        "total_carbohydrate_g": 39,
        "dietary_fiber_g": 0,
        "sugars_g": 39,
        "protein_g": 0,
        "caffeine_mg": 34,
        "category": "Beverages",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Lay's Classic Potato Chips",
        "brand_name": "Frito-Lay",
        "serving_size": "1 oz (28g)",
        "serving_size_grams": 28,
        "calories": 160,
        "total_fat_g": 10,
        "saturated_fat_g": 1.5,
        "trans_fat_g": 0,
        "cholesterol_mg": 0,
        "sodium_mg": 170,
        "total_carbohydrate_g": 15,
        "dietary_fiber_g": 1,
        "sugars_g": 0,
        "protein_g": 2,
        "potassium_mg": 350,
        "category": "Snacks",
        "data_source": "Common Foods Database"
    },
    {
        "name": "KIND Bar - Dark Chocolate Nuts & Sea Salt",
        "brand_name": "KIND",
        "serving_size": "1 bar (40g)",
        "serving_size_grams": 40,
        "calories": 180,
        "total_fat_g": 15,
        "saturated_fat_g": 3.5,
        "trans_fat_g": 0,
        "cholesterol_mg": 0,
        "sodium_mg": 125,
        "total_carbohydrate_g": 16,
        "dietary_fiber_g": 3,
        "sugars_g": 5,
        "protein_g": 6,
        "iron_mg": 0.7,
        "category": "Snacks",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Chobani Greek Yogurt (Plain)",
        "brand_name": "Chobani",
        "serving_size": "1 container (150g)",
        "serving_size_grams": 150,
        "calories": 80,
        "total_fat_g": 0,
        "saturated_fat_g": 0,
        "cholesterol_mg": 5,
        "sodium_mg": 60,
        "total_carbohydrate_g": 6,
        "dietary_fiber_g": 0,
        "sugars_g": 4,
        "protein_g": 15,
        "calcium_mg": 150,
        "category": "Dairy",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Nature Valley Crunchy Granola Bars",
        "brand_name": "Nature Valley",
        "serving_size": "2 bars (42g)",
        "serving_size_grams": 42,
        "calories": 190,
        "total_fat_g": 6,
        "saturated_fat_g": 0.5,
        "trans_fat_g": 0,
        "cholesterol_mg": 0,
        "sodium_mg": 160,
        "total_carbohydrate_g": 29,
        "dietary_fiber_g": 2,
        "sugars_g": 11,
        "protein_g": 4,
        "category": "Snacks",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Goldfish Crackers",
        "brand_name": "Pepperidge Farm",
        "serving_size": "55 pieces (30g)",
        "serving_size_grams": 30,
        "calories": 140,
        "total_fat_g": 5,
        "saturated_fat_g": 1,
        "trans_fat_g": 0,
        "cholesterol_mg": 0,
        "sodium_mg": 250,
        "total_carbohydrate_g": 20,
        "dietary_fiber_g": 1,
        "sugars_g": 0,
        "protein_g": 4,
        "iron_mg": 1.1,
        "category": "Snacks",
        "data_source": "Common Foods Database"
    },
    
    # ========== COMMON PREPARED MEALS ==========
    {
        "name": "Pizza (Pepperoni, large slice)",
        "serving_size": "1 slice (135g)",
        "serving_size_grams": 135,
        "calories": 298,
        "total_fat_g": 12,
        "saturated_fat_g": 5.4,
        "cholesterol_mg": 28,
        "sodium_mg": 683,
        "total_carbohydrate_g": 34,
        "dietary_fiber_g": 2.5,
        "sugars_g": 3.8,
        "protein_g": 13,
        "calcium_mg": 184,
        "iron_mg": 2.5,
        "category": "Prepared Meals",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Hamburger",
        "serving_size": "1 burger (246g)",
        "serving_size_grams": 246,
        "calories": 540,
        "total_fat_g": 27,
        "saturated_fat_g": 10,
        "trans_fat_g": 1.5,
        "cholesterol_mg": 80,
        "sodium_mg": 790,
        "total_carbohydrate_g": 40,
        "dietary_fiber_g": 2,
        "sugars_g": 9,
        "protein_g": 34,
        "iron_mg": 4.8,
        "calcium_mg": 120,
        "category": "Prepared Meals",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Caesar Salad (with dressing)",
        "serving_size": "1 bowl (253g)",
        "serving_size_grams": 253,
        "calories": 358,
        "total_fat_g": 26,
        "saturated_fat_g": 5.2,
        "cholesterol_mg": 23,
        "sodium_mg": 900,
        "total_carbohydrate_g": 22,
        "dietary_fiber_g": 3.3,
        "sugars_g": 3.5,
        "protein_g": 10,
        "vitamin_a_mcg_rae": 523,
        "vitamin_k_mcg": 145,
        "calcium_mg": 190,
        "category": "Prepared Meals",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Chicken Sandwich (grilled)",
        "serving_size": "1 sandwich (228g)",
        "serving_size_grams": 228,
        "calories": 430,
        "total_fat_g": 17,
        "saturated_fat_g": 3.5,
        "cholesterol_mg": 85,
        "sodium_mg": 1110,
        "total_carbohydrate_g": 38,
        "dietary_fiber_g": 2,
        "sugars_g": 8,
        "protein_g": 33,
        "iron_mg": 2.7,
        "category": "Prepared Meals",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Tacos (beef, hard shell)",
        "serving_size": "2 tacos (200g)",
        "serving_size_grams": 200,
        "calories": 420,
        "total_fat_g": 21,
        "saturated_fat_g": 8,
        "cholesterol_mg": 56,
        "sodium_mg": 870,
        "total_carbohydrate_g": 36,
        "dietary_fiber_g": 5,
        "sugars_g": 3,
        "protein_g": 21,
        "calcium_mg": 154,
        "iron_mg": 3.2,
        "category": "Prepared Meals",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Sushi Roll (California)",
        "serving_size": "8 pieces (238g)",
        "serving_size_grams": 238,
        "calories": 255,
        "total_fat_g": 7,
        "saturated_fat_g": 1,
        "cholesterol_mg": 14,
        "sodium_mg": 428,
        "total_carbohydrate_g": 38,
        "dietary_fiber_g": 3,
        "sugars_g": 7,
        "protein_g": 9,
        "iron_mg": 1.5,
        "category": "Prepared Meals",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Burrito Bowl (chicken)",
        "serving_size": "1 bowl (370g)",
        "serving_size_grams": 370,
        "calories": 625,
        "total_fat_g": 21,
        "saturated_fat_g": 7,
        "cholesterol_mg": 125,
        "sodium_mg": 1350,
        "total_carbohydrate_g": 61,
        "dietary_fiber_g": 13,
        "sugars_g": 5,
        "protein_g": 45,
        "vitamin_c_mg": 15,
        "iron_mg": 3,
        "category": "Prepared Meals",
        "data_source": "Common Foods Database"
    },
    
    # ========== BEVERAGES ==========
    {
        "name": "Orange Juice",
        "serving_size": "8 fl oz (240ml)",
        "serving_size_grams": 248,
        "calories": 112,
        "total_fat_g": 0.5,
        "saturated_fat_g": 0.1,
        "cholesterol_mg": 0,
        "sodium_mg": 2,
        "total_carbohydrate_g": 26,
        "dietary_fiber_g": 0.5,
        "sugars_g": 21,
        "protein_g": 1.7,
        "vitamin_c_mg": 124,
        "folate_mcg": 74,
        "potassium_mg": 496,
        "glycemic_index": 50,
        "category": "Beverages",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Coffee (black)",
        "serving_size": "8 fl oz (237ml)",
        "serving_size_grams": 237,
        "calories": 2,
        "total_fat_g": 0,
        "saturated_fat_g": 0,
        "cholesterol_mg": 0,
        "sodium_mg": 5,
        "total_carbohydrate_g": 0,
        "dietary_fiber_g": 0,
        "sugars_g": 0,
        "protein_g": 0.3,
        "caffeine_mg": 95,
        "potassium_mg": 116,
        "magnesium_mg": 7,
        "category": "Beverages",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Protein Shake (whey)",
        "brand_name": "Generic",
        "serving_size": "1 bottle (330ml)",
        "serving_size_grams": 330,
        "calories": 160,
        "total_fat_g": 3,
        "saturated_fat_g": 1,
        "cholesterol_mg": 20,
        "sodium_mg": 180,
        "total_carbohydrate_g": 6,
        "dietary_fiber_g": 0,
        "sugars_g": 2,
        "protein_g": 30,
        "calcium_mg": 450,
        "iron_mg": 0.7,
        "category": "Beverages",
        "data_source": "Common Foods Database"
    },
    
    # ========== DESSERTS ==========
    {
        "name": "Ice Cream (vanilla)",
        "serving_size": "1/2 cup (66g)",
        "serving_size_grams": 66,
        "calories": 137,
        "total_fat_g": 7.3,
        "saturated_fat_g": 4.5,
        "cholesterol_mg": 29,
        "sodium_mg": 53,
        "total_carbohydrate_g": 16,
        "dietary_fiber_g": 0.5,
        "sugars_g": 14,
        "protein_g": 2.3,
        "calcium_mg": 84,
        "vitamin_a_mcg_rae": 78,
        "category": "Desserts",
        "data_source": "Common Foods Database"
    },
    {
        "name": "Chocolate Chip Cookie",
        "serving_size": "1 medium (16g)",
        "serving_size_grams": 16,
        "calories": 78,
        "total_fat_g": 4.5,
        "saturated_fat_g": 2.2,
        "cholesterol_mg": 5,
        "sodium_mg": 55,
        "total_carbohydrate_g": 9.3,
        "dietary_fiber_g": 0.4,
        "sugars_g": 5.2,
        "protein_g": 0.9,
        "iron_mg": 0.4,
        "category": "Desserts",
        "data_source": "Common Foods Database"
    }
]