"""
Extended fast food nutrition data with comprehensive nutrient profiles
"""

FAST_FOOD_NUTRITION_DATA = {
    "McDonald's": [
        {
            "name": "Big Mac",
            "serving_size": "1 sandwich (219g)",
            "serving_size_grams": 219,
            "calories": 563,
            "calories_from_fat": 297,
            "total_fat_g": 33,
            "saturated_fat_g": 11,
            "trans_fat_g": 1.3,
            "polyunsaturated_fat_g": 1.5,
            "monounsaturated_fat_g": 8,
            "cholesterol_mg": 79,
            "sodium_mg": 1010,
            "total_carbohydrate_g": 45,
            "dietary_fiber_g": 3,
            "sugars_g": 9,
            "protein_g": 26,
            "vitamin_a_mcg_rae": 60,
            "vitamin_c_mg": 2,
            "calcium_mg": 120,
            "iron_mg": 4.5,
            "potassium_mg": 390,
            "category": "Burgers"
        },
        {
            "name": "Quarter Pounder with Cheese",
            "serving_size": "1 sandwich (206g)",
            "serving_size_grams": 206,
            "calories": 520,
            "calories_from_fat": 234,
            "total_fat_g": 26,
            "saturated_fat_g": 12,
            "trans_fat_g": 1.5,
            "cholesterol_mg": 95,
            "sodium_mg": 1140,
            "total_carbohydrate_g": 42,
            "dietary_fiber_g": 2,
            "sugars_g": 10,
            "protein_g": 30,
            "calcium_mg": 190,
            "iron_mg": 4.5,
            "potassium_mg": 420,
            "category": "Burgers"
        },
        {
            "name": "McChicken",
            "serving_size": "1 sandwich (147g)",
            "serving_size_grams": 147,
            "calories": 400,
            "total_fat_g": 21,
            "saturated_fat_g": 3.5,
            "trans_fat_g": 0,
            "cholesterol_mg": 35,
            "sodium_mg": 650,
            "total_carbohydrate_g": 39,
            "dietary_fiber_g": 1,
            "sugars_g": 5,
            "protein_g": 14,
            "calcium_mg": 40,
            "iron_mg": 2.7,
            "category": "Chicken"
        },
        {
            "name": "Filet-O-Fish",
            "serving_size": "1 sandwich (141g)",
            "serving_size_grams": 141,
            "calories": 390,
            "total_fat_g": 19,
            "saturated_fat_g": 4,
            "trans_fat_g": 0,
            "cholesterol_mg": 40,
            "sodium_mg": 580,
            "total_carbohydrate_g": 39,
            "dietary_fiber_g": 2,
            "sugars_g": 5,
            "protein_g": 17,
            "calcium_mg": 40,
            "iron_mg": 1.8,
            "omega3_fatty_acids_mg": 150,
            "category": "Fish"
        },
        {
            "name": "Chicken McNuggets (10 piece)",
            "serving_size": "10 pieces (162g)",
            "serving_size_grams": 162,
            "calories": 420,
            "total_fat_g": 25,
            "saturated_fat_g": 4,
            "trans_fat_g": 0,
            "cholesterol_mg": 65,
            "sodium_mg": 840,
            "total_carbohydrate_g": 25,
            "dietary_fiber_g": 1,
            "sugars_g": 0,
            "protein_g": 23,
            "calcium_mg": 20,
            "iron_mg": 0.9,
            "category": "Chicken"
        },
        {
            "name": "Large French Fries",
            "serving_size": "1 large (178g)",
            "serving_size_grams": 178,
            "calories": 490,
            "total_fat_g": 23,
            "saturated_fat_g": 3,
            "trans_fat_g": 0,
            "cholesterol_mg": 0,
            "sodium_mg": 400,
            "total_carbohydrate_g": 66,
            "dietary_fiber_g": 6,
            "sugars_g": 0,
            "protein_g": 7,
            "potassium_mg": 970,
            "vitamin_c_mg": 12,
            "glycemic_index": 75,
            "category": "Sides"
        },
        {
            "name": "Apple Slices",
            "serving_size": "1 package (58g)",
            "serving_size_grams": 58,
            "calories": 15,
            "total_fat_g": 0,
            "saturated_fat_g": 0,
            "cholesterol_mg": 0,
            "sodium_mg": 0,
            "total_carbohydrate_g": 4,
            "dietary_fiber_g": 0,
            "sugars_g": 3,
            "protein_g": 0,
            "vitamin_c_mg": 2,
            "glycemic_index": 36,
            "category": "Sides"
        },
        {
            "name": "Egg McMuffin",
            "serving_size": "1 sandwich (136g)",
            "serving_size_grams": 136,
            "calories": 310,
            "total_fat_g": 13,
            "saturated_fat_g": 6,
            "trans_fat_g": 0,
            "cholesterol_mg": 250,
            "sodium_mg": 770,
            "total_carbohydrate_g": 30,
            "dietary_fiber_g": 2,
            "sugars_g": 3,
            "protein_g": 17,
            "vitamin_a_mcg_rae": 160,
            "calcium_mg": 160,
            "iron_mg": 2.7,
            "vitamin_d_mcg": 1,
            "category": "Breakfast"
        },
        {
            "name": "Hotcakes with Syrup and Butter",
            "serving_size": "3 hotcakes (234g)",
            "serving_size_grams": 234,
            "calories": 580,
            "total_fat_g": 15,
            "saturated_fat_g": 6,
            "trans_fat_g": 0,
            "cholesterol_mg": 45,
            "sodium_mg": 610,
            "total_carbohydrate_g": 101,
            "dietary_fiber_g": 2,
            "sugars_g": 45,
            "protein_g": 9,
            "calcium_mg": 100,
            "iron_mg": 3.6,
            "glycemic_index": 65,
            "category": "Breakfast"
        },
        {
            "name": "Premium Southwest Salad with Grilled Chicken",
            "serving_size": "1 salad (358g)",
            "serving_size_grams": 358,
            "calories": 350,
            "total_fat_g": 12,
            "saturated_fat_g": 4.5,
            "trans_fat_g": 0,
            "cholesterol_mg": 85,
            "sodium_mg": 1070,
            "total_carbohydrate_g": 28,
            "dietary_fiber_g": 7,
            "sugars_g": 6,
            "protein_g": 37,
            "vitamin_a_mcg_rae": 630,
            "vitamin_c_mg": 60,
            "calcium_mg": 280,
            "iron_mg": 3.6,
            "category": "Salads"
        }
    ],
    
    "Burger King": [
        {
            "name": "Whopper",
            "serving_size": "1 sandwich (270g)",
            "serving_size_grams": 270,
            "calories": 657,
            "total_fat_g": 40,
            "saturated_fat_g": 12,
            "trans_fat_g": 1.5,
            "cholesterol_mg": 87,
            "sodium_mg": 983,
            "total_carbohydrate_g": 49,
            "dietary_fiber_g": 2,
            "sugars_g": 11,
            "protein_g": 28,
            "calcium_mg": 80,
            "iron_mg": 6.3,
            "potassium_mg": 500,
            "category": "Burgers"
        },
        {
            "name": "Impossible Whopper",
            "serving_size": "1 sandwich (283g)",
            "serving_size_grams": 283,
            "calories": 629,
            "total_fat_g": 34,
            "saturated_fat_g": 11,
            "trans_fat_g": 0,
            "cholesterol_mg": 10,
            "sodium_mg": 1080,
            "total_carbohydrate_g": 58,
            "dietary_fiber_g": 4,
            "sugars_g": 12,
            "protein_g": 25,
            "calcium_mg": 40,
            "iron_mg": 5.4,
            "vitamin_b12_mcg": 4.5,
            "category": "Burgers"
        },
        {
            "name": "Ch'King Sandwich",
            "serving_size": "1 sandwich (219g)",
            "serving_size_grams": 219,
            "calories": 632,
            "total_fat_g": 38,
            "saturated_fat_g": 7,
            "trans_fat_g": 0,
            "cholesterol_mg": 86,
            "sodium_mg": 1443,
            "total_carbohydrate_g": 48,
            "dietary_fiber_g": 1,
            "sugars_g": 8,
            "protein_g": 24,
            "category": "Chicken"
        },
        {
            "name": "Chicken Fries (9 piece)",
            "serving_size": "9 pieces (92g)",
            "serving_size_grams": 92,
            "calories": 280,
            "total_fat_g": 17,
            "saturated_fat_g": 2.5,
            "trans_fat_g": 0,
            "cholesterol_mg": 35,
            "sodium_mg": 850,
            "total_carbohydrate_g": 20,
            "dietary_fiber_g": 1,
            "sugars_g": 0,
            "protein_g": 14,
            "category": "Chicken"
        },
        {
            "name": "Onion Rings (Medium)",
            "serving_size": "1 medium (117g)",
            "serving_size_grams": 117,
            "calories": 410,
            "total_fat_g": 24,
            "saturated_fat_g": 3.5,
            "trans_fat_g": 0,
            "cholesterol_mg": 0,
            "sodium_mg": 840,
            "total_carbohydrate_g": 48,
            "dietary_fiber_g": 3,
            "sugars_g": 6,
            "protein_g": 4,
            "category": "Sides"
        },
        {
            "name": "Garden Side Salad",
            "serving_size": "1 salad (146g)",
            "serving_size_grams": 146,
            "calories": 60,
            "total_fat_g": 4,
            "saturated_fat_g": 2.5,
            "trans_fat_g": 0,
            "cholesterol_mg": 10,
            "sodium_mg": 95,
            "total_carbohydrate_g": 3,
            "dietary_fiber_g": 1,
            "sugars_g": 2,
            "protein_g": 4,
            "vitamin_a_mcg_rae": 270,
            "vitamin_c_mg": 15,
            "calcium_mg": 80,
            "category": "Salads"
        }
    ],
    
    "Wendy's": [
        {
            "name": "Dave's Single",
            "serving_size": "1 sandwich (248g)",
            "serving_size_grams": 248,
            "calories": 570,
            "total_fat_g": 34,
            "saturated_fat_g": 13,
            "trans_fat_g": 1.5,
            "cholesterol_mg": 100,
            "sodium_mg": 1230,
            "total_carbohydrate_g": 39,
            "dietary_fiber_g": 3,
            "sugars_g": 9,
            "protein_g": 29,
            "calcium_mg": 140,
            "iron_mg": 4.5,
            "category": "Burgers"
        },
        {
            "name": "Baconator",
            "serving_size": "1 sandwich (304g)",
            "serving_size_grams": 304,
            "calories": 950,
            "total_fat_g": 62,
            "saturated_fat_g": 24,
            "trans_fat_g": 3,
            "cholesterol_mg": 205,
            "sodium_mg": 1810,
            "total_carbohydrate_g": 40,
            "dietary_fiber_g": 3,
            "sugars_g": 10,
            "protein_g": 57,
            "category": "Burgers"
        },
        {
            "name": "Spicy Chicken Sandwich",
            "serving_size": "1 sandwich (218g)",
            "serving_size_grams": 218,
            "calories": 490,
            "total_fat_g": 20,
            "saturated_fat_g": 3.5,
            "trans_fat_g": 0,
            "cholesterol_mg": 65,
            "sodium_mg": 1130,
            "total_carbohydrate_g": 51,
            "dietary_fiber_g": 3,
            "sugars_g": 6,
            "protein_g": 28,
            "category": "Chicken"
        },
        {
            "name": "4-Piece Chicken Nuggets",
            "serving_size": "4 pieces (60g)",
            "serving_size_grams": 60,
            "calories": 180,
            "total_fat_g": 11,
            "saturated_fat_g": 2,
            "trans_fat_g": 0,
            "cholesterol_mg": 30,
            "sodium_mg": 380,
            "total_carbohydrate_g": 10,
            "dietary_fiber_g": 0,
            "sugars_g": 0,
            "protein_g": 10,
            "category": "Chicken"
        },
        {
            "name": "Large Chili",
            "serving_size": "1 large (340g)",
            "serving_size_grams": 340,
            "calories": 340,
            "total_fat_g": 17,
            "saturated_fat_g": 7,
            "trans_fat_g": 1,
            "cholesterol_mg": 75,
            "sodium_mg": 1330,
            "total_carbohydrate_g": 24,
            "dietary_fiber_g": 7,
            "sugars_g": 7,
            "protein_g": 25,
            "iron_mg": 4.5,
            "category": "Soups"
        },
        {
            "name": "Apple Pecan Chicken Salad (Full)",
            "serving_size": "1 salad (397g)",
            "serving_size_grams": 397,
            "calories": 460,
            "total_fat_g": 20,
            "saturated_fat_g": 7,
            "trans_fat_g": 0,
            "cholesterol_mg": 105,
            "sodium_mg": 1230,
            "total_carbohydrate_g": 37,
            "dietary_fiber_g": 5,
            "sugars_g": 21,
            "protein_g": 36,
            "vitamin_a_mcg_rae": 630,
            "vitamin_c_mg": 45,
            "calcium_mg": 200,
            "iron_mg": 2.7,
            "category": "Salads"
        },
        {
            "name": "Frosty (Small Chocolate)",
            "serving_size": "1 small (243g)",
            "serving_size_grams": 243,
            "calories": 350,
            "total_fat_g": 9,
            "saturated_fat_g": 6,
            "trans_fat_g": 0,
            "cholesterol_mg": 35,
            "sodium_mg": 150,
            "total_carbohydrate_g": 58,
            "dietary_fiber_g": 0,
            "sugars_g": 47,
            "protein_g": 10,
            "calcium_mg": 300,
            "category": "Desserts"
        }
    ],
    
    "Subway": [
        {
            "name": "6\" Turkey Breast",
            "serving_size": "6 inch sandwich (217g)",
            "serving_size_grams": 217,
            "calories": 280,
            "total_fat_g": 3.5,
            "saturated_fat_g": 1,
            "trans_fat_g": 0,
            "cholesterol_mg": 20,
            "sodium_mg": 760,
            "total_carbohydrate_g": 46,
            "dietary_fiber_g": 5,
            "sugars_g": 7,
            "protein_g": 18,
            "vitamin_a_mcg_rae": 30,
            "vitamin_c_mg": 20,
            "calcium_mg": 60,
            "iron_mg": 2.7,
            "category": "Sandwiches"
        },
        {
            "name": "6\" Italian B.M.T.",
            "serving_size": "6 inch sandwich (236g)",
            "serving_size_grams": 236,
            "calories": 410,
            "total_fat_g": 16,
            "saturated_fat_g": 6,
            "trans_fat_g": 0,
            "cholesterol_mg": 50,
            "sodium_mg": 1260,
            "total_carbohydrate_g": 45,
            "dietary_fiber_g": 5,
            "sugars_g": 7,
            "protein_g": 19,
            "calcium_mg": 60,
            "iron_mg": 2.7,
            "category": "Sandwiches"
        },
        {
            "name": "6\" Veggie Delite",
            "serving_size": "6 inch sandwich (168g)",
            "serving_size_grams": 168,
            "calories": 230,
            "total_fat_g": 2.5,
            "saturated_fat_g": 0.5,
            "trans_fat_g": 0,
            "cholesterol_mg": 0,
            "sodium_mg": 360,
            "total_carbohydrate_g": 45,
            "dietary_fiber_g": 5,
            "sugars_g": 7,
            "protein_g": 9,
            "vitamin_a_mcg_rae": 60,
            "vitamin_c_mg": 30,
            "calcium_mg": 60,
            "iron_mg": 2.7,
            "category": "Sandwiches"
        },
        {
            "name": "Footlong Meatball Marinara",
            "serving_size": "12 inch sandwich (453g)",
            "serving_size_grams": 453,
            "calories": 960,
            "total_fat_g": 36,
            "saturated_fat_g": 14,
            "trans_fat_g": 0,
            "cholesterol_mg": 80,
            "sodium_mg": 1840,
            "total_carbohydrate_g": 112,
            "dietary_fiber_g": 10,
            "sugars_g": 18,
            "protein_g": 40,
            "calcium_mg": 160,
            "iron_mg": 6.3,
            "category": "Sandwiches"
        },
        {
            "name": "Chicken Caesar Wrap",
            "serving_size": "1 wrap (245g)",
            "serving_size_grams": 245,
            "calories": 540,
            "total_fat_g": 26,
            "saturated_fat_g": 7,
            "trans_fat_g": 0,
            "cholesterol_mg": 75,
            "sodium_mg": 1160,
            "total_carbohydrate_g": 46,
            "dietary_fiber_g": 3,
            "sugars_g": 4,
            "protein_g": 31,
            "vitamin_a_mcg_rae": 150,
            "calcium_mg": 250,
            "category": "Wraps"
        },
        {
            "name": "Chocolate Chip Cookie",
            "serving_size": "1 cookie (45g)",
            "serving_size_grams": 45,
            "calories": 220,
            "total_fat_g": 10,
            "saturated_fat_g": 5,
            "trans_fat_g": 0,
            "cholesterol_mg": 15,
            "sodium_mg": 120,
            "total_carbohydrate_g": 30,
            "dietary_fiber_g": 1,
            "sugars_g": 18,
            "protein_g": 2,
            "category": "Desserts"
        }
    ],
    
    "Taco Bell": [
        {
            "name": "Crunchy Taco",
            "serving_size": "1 taco (94g)",
            "serving_size_grams": 94,
            "calories": 170,
            "total_fat_g": 9,
            "saturated_fat_g": 3.5,
            "trans_fat_g": 0,
            "cholesterol_mg": 25,
            "sodium_mg": 310,
            "total_carbohydrate_g": 13,
            "dietary_fiber_g": 3,
            "sugars_g": 1,
            "protein_g": 8,
            "calcium_mg": 60,
            "category": "Tacos"
        },
        {
            "name": "Crunchy Taco Supreme",
            "serving_size": "1 taco (113g)",
            "serving_size_grams": 113,
            "calories": 190,
            "total_fat_g": 11,
            "saturated_fat_g": 5,
            "trans_fat_g": 0,
            "cholesterol_mg": 35,
            "sodium_mg": 340,
            "total_carbohydrate_g": 15,
            "dietary_fiber_g": 3,
            "sugars_g": 2,
            "protein_g": 9,
            "calcium_mg": 80,
            "category": "Tacos"
        },
        {
            "name": "Soft Taco",
            "serving_size": "1 taco (100g)",
            "serving_size_grams": 100,
            "calories": 180,
            "total_fat_g": 8,
            "saturated_fat_g": 3.5,
            "trans_fat_g": 0,
            "cholesterol_mg": 25,
            "sodium_mg": 480,
            "total_carbohydrate_g": 18,
            "dietary_fiber_g": 2,
            "sugars_g": 1,
            "protein_g": 9,
            "calcium_mg": 60,
            "category": "Tacos"
        },
        {
            "name": "Crunchwrap Supreme",
            "serving_size": "1 crunchwrap (252g)",
            "serving_size_grams": 252,
            "calories": 530,
            "total_fat_g": 21,
            "saturated_fat_g": 7,
            "trans_fat_g": 0,
            "cholesterol_mg": 35,
            "sodium_mg": 1200,
            "total_carbohydrate_g": 71,
            "dietary_fiber_g": 6,
            "sugars_g": 6,
            "protein_g": 16,
            "calcium_mg": 140,
            "iron_mg": 3.6,
            "category": "Specialty Items"
        },
        {
            "name": "Burrito Supreme - Beef",
            "serving_size": "1 burrito (248g)",
            "serving_size_grams": 248,
            "calories": 400,
            "total_fat_g": 16,
            "saturated_fat_g": 8,
            "trans_fat_g": 0,
            "cholesterol_mg": 40,
            "sodium_mg": 1110,
            "total_carbohydrate_g": 49,
            "dietary_fiber_g": 6,
            "sugars_g": 4,
            "protein_g": 16,
            "calcium_mg": 160,
            "category": "Burritos"
        },
        {
            "name": "Quesadilla - Cheese",
            "serving_size": "1 quesadilla (156g)",
            "serving_size_grams": 156,
            "calories": 470,
            "total_fat_g": 26,
            "saturated_fat_g": 12,
            "trans_fat_g": 0,
            "cholesterol_mg": 50,
            "sodium_mg": 1050,
            "total_carbohydrate_g": 38,
            "dietary_fiber_g": 3,
            "sugars_g": 3,
            "protein_g": 19,
            "calcium_mg": 400,
            "category": "Quesadillas"
        },
        {
            "name": "Mexican Pizza",
            "serving_size": "1 pizza (213g)",
            "serving_size_grams": 213,
            "calories": 530,
            "total_fat_g": 29,
            "saturated_fat_g": 9,
            "trans_fat_g": 0,
            "cholesterol_mg": 45,
            "sodium_mg": 990,
            "total_carbohydrate_g": 49,
            "dietary_fiber_g": 5,
            "sugars_g": 4,
            "protein_g": 18,
            "calcium_mg": 240,
            "category": "Specialty Items"
        },
        {
            "name": "Nachos BellGrande",
            "serving_size": "1 serving (308g)",
            "serving_size_grams": 308,
            "calories": 740,
            "total_fat_g": 38,
            "saturated_fat_g": 7,
            "trans_fat_g": 0,
            "cholesterol_mg": 35,
            "sodium_mg": 1050,
            "total_carbohydrate_g": 82,
            "dietary_fiber_g": 12,
            "sugars_g": 4,
            "protein_g": 16,
            "calcium_mg": 160,
            "category": "Nachos"
        },
        {
            "name": "Cinnamon Twists",
            "serving_size": "1 serving (35g)",
            "serving_size_grams": 35,
            "calories": 170,
            "total_fat_g": 6,
            "saturated_fat_g": 0,
            "trans_fat_g": 0,
            "cholesterol_mg": 0,
            "sodium_mg": 200,
            "total_carbohydrate_g": 27,
            "dietary_fiber_g": 1,
            "sugars_g": 12,
            "protein_g": 1,
            "category": "Desserts"
        }
    ],
    
    "KFC": [
        {
            "name": "Original Recipe Chicken Breast",
            "serving_size": "1 breast (187g)",
            "serving_size_grams": 187,
            "calories": 390,
            "total_fat_g": 21,
            "saturated_fat_g": 4,
            "trans_fat_g": 0,
            "cholesterol_mg": 145,
            "sodium_mg": 1190,
            "total_carbohydrate_g": 11,
            "dietary_fiber_g": 0,
            "sugars_g": 0,
            "protein_g": 39,
            "calcium_mg": 40,
            "iron_mg": 1.8,
            "category": "Chicken"
        },
        {
            "name": "Extra Crispy Chicken Breast",
            "serving_size": "1 breast (176g)",
            "serving_size_grams": 176,
            "calories": 530,
            "total_fat_g": 35,
            "saturated_fat_g": 6,
            "trans_fat_g": 0,
            "cholesterol_mg": 105,
            "sodium_mg": 1150,
            "total_carbohydrate_g": 18,
            "dietary_fiber_g": 1,
            "sugars_g": 0,
            "protein_g": 35,
            "category": "Chicken"
        },
        {
            "name": "Original Recipe Chicken Thigh",
            "serving_size": "1 thigh (119g)",
            "serving_size_grams": 119,
            "calories": 280,
            "total_fat_g": 18,
            "saturated_fat_g": 4,
            "trans_fat_g": 0,
            "cholesterol_mg": 125,
            "sodium_mg": 870,
            "total_carbohydrate_g": 7,
            "dietary_fiber_g": 0,
            "sugars_g": 0,
            "protein_g": 21,
            "category": "Chicken"
        },
        {
            "name": "Popcorn Nuggets (Large)",
            "serving_size": "1 large (128g)",
            "serving_size_grams": 128,
            "calories": 570,
            "total_fat_g": 36,
            "saturated_fat_g": 6,
            "trans_fat_g": 0,
            "cholesterol_mg": 60,
            "sodium_mg": 1760,
            "total_carbohydrate_g": 36,
            "dietary_fiber_g": 3,
            "sugars_g": 0,
            "protein_g": 22,
            "category": "Chicken"
        },
        {
            "name": "Famous Bowl",
            "serving_size": "1 bowl (426g)",
            "serving_size_grams": 426,
            "calories": 710,
            "total_fat_g": 31,
            "saturated_fat_g": 9,
            "trans_fat_g": 0,
            "cholesterol_mg": 60,
            "sodium_mg": 2450,
            "total_carbohydrate_g": 79,
            "dietary_fiber_g": 6,
            "sugars_g": 3,
            "protein_g": 26,
            "vitamin_a_mcg_rae": 60,
            "calcium_mg": 150,
            "iron_mg": 2.7,
            "category": "Bowls"
        },
        {
            "name": "Mashed Potatoes with Gravy",
            "serving_size": "1 serving (151g)",
            "serving_size_grams": 151,
            "calories": 120,
            "total_fat_g": 4.5,
            "saturated_fat_g": 1,
            "trans_fat_g": 0,
            "cholesterol_mg": 0,
            "sodium_mg": 530,
            "total_carbohydrate_g": 19,
            "dietary_fiber_g": 1,
            "sugars_g": 0,
            "protein_g": 2,
            "category": "Sides"
        },
        {
            "name": "Cole Slaw",
            "serving_size": "1 serving (142g)",
            "serving_size_grams": 142,
            "calories": 170,
            "total_fat_g": 12,
            "saturated_fat_g": 2,
            "trans_fat_g": 0,
            "cholesterol_mg": 5,
            "sodium_mg": 180,
            "total_carbohydrate_g": 14,
            "dietary_fiber_g": 3,
            "sugars_g": 10,
            "protein_g": 1,
            "vitamin_c_mg": 30,
            "category": "Sides"
        },
        {
            "name": "Biscuit",
            "serving_size": "1 biscuit (60g)",
            "serving_size_grams": 60,
            "calories": 180,
            "total_fat_g": 8,
            "saturated_fat_g": 4.5,
            "trans_fat_g": 0,
            "cholesterol_mg": 0,
            "sodium_mg": 530,
            "total_carbohydrate_g": 24,
            "dietary_fiber_g": 1,
            "sugars_g": 2,
            "protein_g": 4,
            "category": "Sides"
        }
    ],
    
    "Chipotle": [
        {
            "name": "Chicken Burrito Bowl (with rice, black beans, cheese, salsa)",
            "serving_size": "1 bowl (540g)",
            "serving_size_grams": 540,
            "calories": 625,
            "total_fat_g": 22.5,
            "saturated_fat_g": 8,
            "trans_fat_g": 0,
            "cholesterol_mg": 125,
            "sodium_mg": 1330,
            "total_carbohydrate_g": 58,
            "dietary_fiber_g": 10.5,
            "sugars_g": 4,
            "protein_g": 45,
            "vitamin_a_mcg_rae": 225,
            "vitamin_c_mg": 13.5,
            "calcium_mg": 205,
            "iron_mg": 3.2,
            "category": "Bowls"
        },
        {
            "name": "Steak Burrito (tortilla, rice, beans, steak, cheese, salsa)",
            "serving_size": "1 burrito (566g)",
            "serving_size_grams": 566,
            "calories": 915,
            "total_fat_g": 32,
            "saturated_fat_g": 12,
            "trans_fat_g": 0,
            "cholesterol_mg": 85,
            "sodium_mg": 1870,
            "total_carbohydrate_g": 102,
            "dietary_fiber_g": 13,
            "sugars_g": 5,
            "protein_g": 43,
            "calcium_mg": 260,
            "iron_mg": 5.4,
            "category": "Burritos"
        },
        {
            "name": "Carnitas Tacos (3 soft tacos)",
            "serving_size": "3 tacos (352g)",
            "serving_size_grams": 352,
            "calories": 710,
            "total_fat_g": 35,
            "saturated_fat_g": 12,
            "trans_fat_g": 0,
            "cholesterol_mg": 105,
            "sodium_mg": 1490,
            "total_carbohydrate_g": 60,
            "dietary_fiber_g": 11,
            "sugars_g": 3,
            "protein_g": 37,
            "category": "Tacos"
        },
        {
            "name": "Sofritas Bowl (vegan protein)",
            "serving_size": "1 bowl (540g)",
            "serving_size_grams": 540,
            "calories": 520,
            "total_fat_g": 17,
            "saturated_fat_g": 3,
            "trans_fat_g": 0,
            "cholesterol_mg": 0,
            "sodium_mg": 1115,
            "total_carbohydrate_g": 66,
            "dietary_fiber_g": 12.5,
            "sugars_g": 5,
            "protein_g": 20,
            "calcium_mg": 140,
            "iron_mg": 4.5,
            "category": "Bowls"
        },
        {
            "name": "Chips and Guacamole",
            "serving_size": "1 serving (198g)",
            "serving_size_grams": 198,
            "calories": 770,
            "total_fat_g": 47,
            "saturated_fat_g": 6.5,
            "trans_fat_g": 0,
            "cholesterol_mg": 0,
            "sodium_mg": 520,
            "total_carbohydrate_g": 82,
            "dietary_fiber_g": 14,
            "sugars_g": 6,
            "protein_g": 10,
            "vitamin_c_mg": 18,
            "potassium_mg": 970,
            "category": "Sides"
        },
        {
            "name": "Quesadilla with Chicken",
            "serving_size": "1 quesadilla (329g)",
            "serving_size_grams": 329,
            "calories": 865,
            "total_fat_g": 45.5,
            "saturated_fat_g": 22,
            "trans_fat_g": 0,
            "cholesterol_mg": 150,
            "sodium_mg": 1515,
            "total_carbohydrate_g": 60,
            "dietary_fiber_g": 4,
            "sugars_g": 3,
            "protein_g": 52,
            "calcium_mg": 680,
            "category": "Quesadillas"
        }
    ],
    
    "Starbucks": [
        {
            "name": "Bacon & Gouda Breakfast Sandwich",
            "serving_size": "1 sandwich (133g)",
            "serving_size_grams": 133,
            "calories": 370,
            "total_fat_g": 19,
            "saturated_fat_g": 7,
            "trans_fat_g": 0,
            "cholesterol_mg": 180,
            "sodium_mg": 870,
            "total_carbohydrate_g": 32,
            "dietary_fiber_g": 1,
            "sugars_g": 4,
            "protein_g": 17,
            "calcium_mg": 150,
            "iron_mg": 2,
            "category": "Breakfast"
        },
        {
            "name": "Spinach, Feta & Egg White Wrap",
            "serving_size": "1 wrap (156g)",
            "serving_size_grams": 156,
            "calories": 290,
            "total_fat_g": 8,
            "saturated_fat_g": 3.5,
            "trans_fat_g": 0,
            "cholesterol_mg": 20,
            "sodium_mg": 830,
            "total_carbohydrate_g": 34,
            "dietary_fiber_g": 7,
            "sugars_g": 5,
            "protein_g": 20,
            "vitamin_a_mcg_rae": 270,
            "calcium_mg": 250,
            "iron_mg": 3.6,
            "category": "Breakfast"
        },
        {
            "name": "Turkey Bacon & Cheddar Egg Sandwich",
            "serving_size": "1 sandwich (125g)",
            "serving_size_grams": 125,
            "calories": 230,
            "total_fat_g": 5,
            "saturated_fat_g": 2,
            "trans_fat_g": 0,
            "cholesterol_mg": 155,
            "sodium_mg": 580,
            "total_carbohydrate_g": 28,
            "dietary_fiber_g": 1,
            "sugars_g": 3,
            "protein_g": 17,
            "calcium_mg": 100,
            "category": "Breakfast"
        },
        {
            "name": "Chocolate Croissant",
            "serving_size": "1 croissant (85g)",
            "serving_size_grams": 85,
            "calories": 340,
            "total_fat_g": 19,
            "saturated_fat_g": 11,
            "trans_fat_g": 0,
            "cholesterol_mg": 35,
            "sodium_mg": 260,
            "total_carbohydrate_g": 38,
            "dietary_fiber_g": 2,
            "sugars_g": 11,
            "protein_g": 6,
            "category": "Bakery"
        },
        {
            "name": "Blueberry Muffin",
            "serving_size": "1 muffin (131g)",
            "serving_size_grams": 131,
            "calories": 360,
            "total_fat_g": 15,
            "saturated_fat_g": 2,
            "trans_fat_g": 0,
            "cholesterol_mg": 50,
            "sodium_mg": 320,
            "total_carbohydrate_g": 52,
            "dietary_fiber_g": 1,
            "sugars_g": 29,
            "protein_g": 5,
            "category": "Bakery"
        },
        {
            "name": "Protein Box - Cheese & Fruit",
            "serving_size": "1 box (196g)",
            "serving_size_grams": 196,
            "calories": 470,
            "total_fat_g": 28,
            "saturated_fat_g": 10,
            "trans_fat_g": 0,
            "cholesterol_mg": 60,
            "sodium_mg": 580,
            "total_carbohydrate_g": 37,
            "dietary_fiber_g": 5,
            "sugars_g": 20,
            "protein_g": 20,
            "calcium_mg": 300,
            "vitamin_c_mg": 60,
            "category": "Protein Boxes"
        },
        {
            "name": "Caesar Salad with Chicken",
            "serving_size": "1 salad (234g)",
            "serving_size_grams": 234,
            "calories": 350,
            "total_fat_g": 20,
            "saturated_fat_g": 4.5,
            "trans_fat_g": 0,
            "cholesterol_mg": 95,
            "sodium_mg": 930,
            "total_carbohydrate_g": 13,
            "dietary_fiber_g": 3,
            "sugars_g": 2,
            "protein_g": 30,
            "vitamin_a_mcg_rae": 540,
            "calcium_mg": 150,
            "category": "Salads"
        }
    ],
    
    "Panera Bread": [
        {
            "name": "Mac & Cheese (Bread Bowl)",
            "serving_size": "1 bread bowl (895g)",
            "serving_size_grams": 895,
            "calories": 1380,
            "total_fat_g": 52,
            "saturated_fat_g": 28,
            "trans_fat_g": 1,
            "cholesterol_mg": 135,
            "sodium_mg": 2840,
            "total_carbohydrate_g": 169,
            "dietary_fiber_g": 7,
            "sugars_g": 15,
            "protein_g": 53,
            "calcium_mg": 800,
            "category": "Pasta"
        },
        {
            "name": "Broccoli Cheddar Soup (Bowl)",
            "serving_size": "1 bowl (340g)",
            "serving_size_grams": 340,
            "calories": 360,
            "total_fat_g": 21,
            "saturated_fat_g": 11,
            "trans_fat_g": 0,
            "cholesterol_mg": 60,
            "sodium_mg": 1330,
            "total_carbohydrate_g": 30,
            "dietary_fiber_g": 2,
            "sugars_g": 6,
            "protein_g": 14,
            "vitamin_a_mcg_rae": 540,
            "calcium_mg": 320,
            "vitamin_c_mg": 36,
            "category": "Soups"
        },
        {
            "name": "Turkey Sandwich",
            "serving_size": "1 sandwich (320g)",
            "serving_size_grams": 320,
            "calories": 510,
            "total_fat_g": 14,
            "saturated_fat_g": 3,
            "trans_fat_g": 0,
            "cholesterol_mg": 65,
            "sodium_mg": 1840,
            "total_carbohydrate_g": 65,
            "dietary_fiber_g": 4,
            "sugars_g": 8,
            "protein_g": 29,
            "category": "Sandwiches"
        },
        {
            "name": "Caesar Salad",
            "serving_size": "1 salad (284g)",
            "serving_size_grams": 284,
            "calories": 410,
            "total_fat_g": 27,
            "saturated_fat_g": 7,
            "trans_fat_g": 0,
            "cholesterol_mg": 60,
            "sodium_mg": 820,
            "total_carbohydrate_g": 29,
            "dietary_fiber_g": 3,
            "sugars_g": 5,
            "protein_g": 13,
            "vitamin_a_mcg_rae": 360,
            "category": "Salads"
        },
        {
            "name": "Chocolate Chip Cookie",
            "serving_size": "1 cookie (110g)",
            "serving_size_grams": 110,
            "calories": 440,
            "total_fat_g": 17,
            "saturated_fat_g": 10,
            "trans_fat_g": 0,
            "cholesterol_mg": 45,
            "sodium_mg": 380,
            "total_carbohydrate_g": 68,
            "dietary_fiber_g": 2,
            "sugars_g": 39,
            "protein_g": 5,
            "category": "Bakery"
        }
    ],
    
    "Chick-fil-A": [
        {
            "name": "Original Chicken Sandwich",
            "serving_size": "1 sandwich (183g)",
            "serving_size_grams": 183,
            "calories": 440,
            "total_fat_g": 19,
            "saturated_fat_g": 4,
            "trans_fat_g": 0,
            "cholesterol_mg": 70,
            "sodium_mg": 1400,
            "total_carbohydrate_g": 40,
            "dietary_fiber_g": 1,
            "sugars_g": 5,
            "protein_g": 28,
            "calcium_mg": 150,
            "iron_mg": 2.7,
            "category": "Sandwiches"
        },
        {
            "name": "Spicy Deluxe Sandwich",
            "serving_size": "1 sandwich (254g)",
            "serving_size_grams": 254,
            "calories": 550,
            "total_fat_g": 25,
            "saturated_fat_g": 8,
            "trans_fat_g": 0,
            "cholesterol_mg": 85,
            "sodium_mg": 1810,
            "total_carbohydrate_g": 43,
            "dietary_fiber_g": 2,
            "sugars_g": 6,
            "protein_g": 34,
            "vitamin_a_mcg_rae": 60,
            "category": "Sandwiches"
        },
        {
            "name": "Grilled Chicken Sandwich",
            "serving_size": "1 sandwich (209g)",
            "serving_size_grams": 209,
            "calories": 320,
            "total_fat_g": 6,
            "saturated_fat_g": 1.5,
            "trans_fat_g": 0,
            "cholesterol_mg": 70,
            "sodium_mg": 800,
            "total_carbohydrate_g": 41,
            "dietary_fiber_g": 3,
            "sugars_g": 9,
            "protein_g": 30,
            "category": "Sandwiches"
        },
        {
            "name": "8-count Nuggets",
            "serving_size": "8 nuggets (113g)",
            "serving_size_grams": 113,
            "calories": 250,
            "total_fat_g": 11,
            "saturated_fat_g": 2.5,
            "trans_fat_g": 0,
            "cholesterol_mg": 85,
            "sodium_mg": 1210,
            "total_carbohydrate_g": 11,
            "dietary_fiber_g": 0,
            "sugars_g": 1,
            "protein_g": 27,
            "category": "Nuggets"
        },
        {
            "name": "Waffle Potato Fries (Medium)",
            "serving_size": "1 medium (125g)",
            "serving_size_grams": 125,
            "calories": 420,
            "total_fat_g": 24,
            "saturated_fat_g": 4,
            "trans_fat_g": 0,
            "cholesterol_mg": 0,
            "sodium_mg": 240,
            "total_carbohydrate_g": 45,
            "dietary_fiber_g": 5,
            "sugars_g": 1,
            "protein_g": 5,
            "potassium_mg": 680,
            "category": "Sides"
        },
        {
            "name": "Cobb Salad with Grilled Chicken",
            "serving_size": "1 salad (418g)",
            "serving_size_grams": 418,
            "calories": 510,
            "total_fat_g": 27,
            "saturated_fat_g": 7,
            "trans_fat_g": 0,
            "cholesterol_mg": 185,
            "sodium_mg": 1360,
            "total_carbohydrate_g": 28,
            "dietary_fiber_g": 5,
            "sugars_g": 6,
            "protein_g": 40,
            "vitamin_a_mcg_rae": 540,
            "vitamin_c_mg": 30,
            "calcium_mg": 150,
            "category": "Salads"
        },
        {
            "name": "Frosted Lemonade",
            "serving_size": "1 small (290g)",
            "serving_size_grams": 290,
            "calories": 330,
            "total_fat_g": 6,
            "saturated_fat_g": 3.5,
            "trans_fat_g": 0,
            "cholesterol_mg": 25,
            "sodium_mg": 120,
            "total_carbohydrate_g": 65,
            "dietary_fiber_g": 0,
            "sugars_g": 63,
            "protein_g": 6,
            "calcium_mg": 200,
            "category": "Beverages"
        }
    ],
    
    "Five Guys": [
        {
            "name": "Hamburger",
            "serving_size": "1 burger (242g)",
            "serving_size_grams": 242,
            "calories": 700,
            "total_fat_g": 43,
            "saturated_fat_g": 19.5,
            "trans_fat_g": 2,
            "cholesterol_mg": 125,
            "sodium_mg": 430,
            "total_carbohydrate_g": 39,
            "dietary_fiber_g": 2,
            "sugars_g": 8,
            "protein_g": 39,
            "calcium_mg": 120,
            "iron_mg": 4.5,
            "category": "Burgers"
        },
        {
            "name": "Cheeseburger",
            "serving_size": "1 burger (283g)",
            "serving_size_grams": 283,
            "calories": 840,
            "total_fat_g": 55,
            "saturated_fat_g": 26,
            "trans_fat_g": 2,
            "cholesterol_mg": 165,
            "sodium_mg": 1050,
            "total_carbohydrate_g": 40,
            "dietary_fiber_g": 2,
            "sugars_g": 9,
            "protein_g": 47,
            "calcium_mg": 360,
            "category": "Burgers"
        },
        {
            "name": "Bacon Burger",
            "serving_size": "1 burger (282g)",
            "serving_size_grams": 282,
            "calories": 780,
            "total_fat_g": 50,
            "saturated_fat_g": 22,
            "trans_fat_g": 2,
            "cholesterol_mg": 145,
            "sodium_mg": 760,
            "total_carbohydrate_g": 39,
            "dietary_fiber_g": 2,
            "sugars_g": 8,
            "protein_g": 43,
            "category": "Burgers"
        },
        {
            "name": "Little Hamburger",
            "serving_size": "1 burger (158g)",
            "serving_size_grams": 158,
            "calories": 480,
            "total_fat_g": 26,
            "saturated_fat_g": 11.5,
            "trans_fat_g": 1,
            "cholesterol_mg": 70,
            "sodium_mg": 380,
            "total_carbohydrate_g": 39,
            "dietary_fiber_g": 2,
            "sugars_g": 8,
            "protein_g": 23,
            "category": "Burgers"
        },
        {
            "name": "Regular Fries",
            "serving_size": "1 regular (411g)",
            "serving_size_grams": 411,
            "calories": 620,
            "total_fat_g": 30,
            "saturated_fat_g": 6,
            "trans_fat_g": 0,
            "cholesterol_mg": 0,
            "sodium_mg": 90,
            "total_carbohydrate_g": 78,
            "dietary_fiber_g": 8,
            "sugars_g": 2,
            "protein_g": 8,
            "potassium_mg": 1470,
            "category": "Sides"
        },
        {
            "name": "Grilled Cheese",
            "serving_size": "1 sandwich (136g)",
            "serving_size_grams": 136,
            "calories": 470,
            "total_fat_g": 26,
            "saturated_fat_g": 14,
            "trans_fat_g": 0.5,
            "cholesterol_mg": 60,
            "sodium_mg": 1090,
            "total_carbohydrate_g": 40,
            "dietary_fiber_g": 2,
            "sugars_g": 9,
            "protein_g": 18,
            "calcium_mg": 400,
            "category": "Sandwiches"
        },
        {
            "name": "Hot Dog",
            "serving_size": "1 hot dog (181g)",
            "serving_size_grams": 181,
            "calories": 520,
            "total_fat_g": 35,
            "saturated_fat_g": 15,
            "trans_fat_g": 2,
            "cholesterol_mg": 60,
            "sodium_mg": 1130,
            "total_carbohydrate_g": 40,
            "dietary_fiber_g": 2,
            "sugars_g": 8,
            "protein_g": 18,
            "category": "Hot Dogs"
        }
    ],
    
    "Domino's": [
        {
            "name": "Pepperoni Pizza (Large, Hand Tossed, 1 slice)",
            "serving_size": "1 slice (121g)",
            "serving_size_grams": 121,
            "calories": 300,
            "total_fat_g": 12,
            "saturated_fat_g": 5,
            "trans_fat_g": 0,
            "cholesterol_mg": 25,
            "sodium_mg": 700,
            "total_carbohydrate_g": 34,
            "dietary_fiber_g": 2,
            "sugars_g": 3,
            "protein_g": 13,
            "calcium_mg": 150,
            "glycemic_index": 60,
            "category": "Pizza"
        },
        {
            "name": "Cheese Pizza (Large, Hand Tossed, 1 slice)",
            "serving_size": "1 slice (108g)",
            "serving_size_grams": 108,
            "calories": 290,
            "total_fat_g": 11,
            "saturated_fat_g": 5,
            "trans_fat_g": 0,
            "cholesterol_mg": 25,
            "sodium_mg": 590,
            "total_carbohydrate_g": 34,
            "dietary_fiber_g": 2,
            "sugars_g": 3,
            "protein_g": 12,
            "calcium_mg": 180,
            "category": "Pizza"
        },
        {
            "name": "ExtravaganZZa (Large, Hand Tossed, 1 slice)",
            "serving_size": "1 slice (149g)",
            "serving_size_grams": 149,
            "calories": 380,
            "total_fat_g": 18,
            "saturated_fat_g": 8,
            "trans_fat_g": 0,
            "cholesterol_mg": 40,
            "sodium_mg": 930,
            "total_carbohydrate_g": 35,
            "dietary_fiber_g": 2,
            "sugars_g": 3,
            "protein_g": 16,
            "category": "Pizza"
        },
        {
            "name": "Buffalo Chicken Wings (8 pieces)",
            "serving_size": "8 wings (216g)",
            "serving_size_grams": 216,
            "calories": 640,
            "total_fat_g": 42,
            "saturated_fat_g": 15,
            "trans_fat_g": 0,
            "cholesterol_mg": 180,
            "sodium_mg": 2080,
            "total_carbohydrate_g": 6,
            "dietary_fiber_g": 0,
            "sugars_g": 0,
            "protein_g": 60,
            "category": "Wings"
        },
        {
            "name": "Cheesy Bread (1 piece)",
            "serving_size": "1 piece (35g)",
            "serving_size_grams": 35,
            "calories": 120,
            "total_fat_g": 6,
            "saturated_fat_g": 2.5,
            "trans_fat_g": 0,
            "cholesterol_mg": 10,
            "sodium_mg": 200,
            "total_carbohydrate_g": 13,
            "dietary_fiber_g": 0,
            "sugars_g": 1,
            "protein_g": 4,
            "category": "Sides"
        },
        {
            "name": "Cinnamon Bread Twists (1 piece)",
            "serving_size": "1 piece (31g)",
            "serving_size_grams": 31,
            "calories": 120,
            "total_fat_g": 6,
            "saturated_fat_g": 1,
            "trans_fat_g": 0,
            "cholesterol_mg": 0,
            "sodium_mg": 85,
            "total_carbohydrate_g": 15,
            "dietary_fiber_g": 0,
            "sugars_g": 3,
            "protein_g": 2,
            "category": "Desserts"
        }
    ],
    
    "Pizza Hut": [
        {
            "name": "Pepperoni Pizza (Large, Pan, 1 slice)",
            "serving_size": "1 slice (119g)",
            "serving_size_grams": 119,
            "calories": 370,
            "total_fat_g": 19,
            "saturated_fat_g": 7,
            "trans_fat_g": 0,
            "cholesterol_mg": 30,
            "sodium_mg": 750,
            "total_carbohydrate_g": 35,
            "dietary_fiber_g": 2,
            "sugars_g": 2,
            "protein_g": 15,
            "calcium_mg": 200,
            "category": "Pizza"
        },
        {
            "name": "Meat Lover's Pizza (Large, Pan, 1 slice)",
            "serving_size": "1 slice (143g)",
            "serving_size_grams": 143,
            "calories": 470,
            "total_fat_g": 28,
            "saturated_fat_g": 11,
            "trans_fat_g": 0.5,
            "cholesterol_mg": 50,
            "sodium_mg": 1070,
            "total_carbohydrate_g": 35,
            "dietary_fiber_g": 2,
            "sugars_g": 2,
            "protein_g": 20,
            "category": "Pizza"
        },
        {
            "name": "Veggie Lover's Pizza (Large, Pan, 1 slice)",
            "serving_size": "1 slice (135g)",
            "serving_size_grams": 135,
            "calories": 340,
            "total_fat_g": 16,
            "saturated_fat_g": 6,
            "trans_fat_g": 0,
            "cholesterol_mg": 25,
            "sodium_mg": 680,
            "total_carbohydrate_g": 37,
            "dietary_fiber_g": 3,
            "sugars_g": 3,
            "protein_g": 13,
            "vitamin_a_mcg_rae": 90,
            "vitamin_c_mg": 6,
            "category": "Pizza"
        },
        {
            "name": "Boneless Wings (8 pieces)",
            "serving_size": "8 wings (185g)",
            "serving_size_grams": 185,
            "calories": 470,
            "total_fat_g": 23,
            "saturated_fat_g": 5,
            "trans_fat_g": 0,
            "cholesterol_mg": 75,
            "sodium_mg": 1680,
            "total_carbohydrate_g": 39,
            "dietary_fiber_g": 2,
            "sugars_g": 0,
            "protein_g": 28,
            "category": "Wings"
        },
        {
            "name": "Breadsticks (1 breadstick)",
            "serving_size": "1 breadstick (53g)",
            "serving_size_grams": 53,
            "calories": 140,
            "total_fat_g": 5,
            "saturated_fat_g": 1,
            "trans_fat_g": 0,
            "cholesterol_mg": 0,
            "sodium_mg": 260,
            "total_carbohydrate_g": 19,
            "dietary_fiber_g": 1,
            "sugars_g": 2,
            "protein_g": 4,
            "category": "Sides"
        },
        {
            "name": "Cinnamon Sticks (2 sticks)",
            "serving_size": "2 sticks (55g)",
            "serving_size_grams": 55,
            "calories": 170,
            "total_fat_g": 4.5,
            "saturated_fat_g": 1,
            "trans_fat_g": 0,
            "cholesterol_mg": 0,
            "sodium_mg": 170,
            "total_carbohydrate_g": 31,
            "dietary_fiber_g": 1,
            "sugars_g": 8,
            "protein_g": 3,
            "category": "Desserts"
        }
    ],
    
    "In-N-Out": [
        {
            "name": "Hamburger",
            "serving_size": "1 burger (243g)",
            "serving_size_grams": 243,
            "calories": 390,
            "total_fat_g": 19,
            "saturated_fat_g": 5,
            "trans_fat_g": 0,
            "cholesterol_mg": 40,
            "sodium_mg": 650,
            "total_carbohydrate_g": 39,
            "dietary_fiber_g": 3,
            "sugars_g": 10,
            "protein_g": 16,
            "calcium_mg": 80,
            "iron_mg": 3.6,
            "category": "Burgers"
        },
        {
            "name": "Cheeseburger",
            "serving_size": "1 burger (268g)",
            "serving_size_grams": 268,
            "calories": 480,
            "total_fat_g": 27,
            "saturated_fat_g": 10,
            "trans_fat_g": 0.5,
            "cholesterol_mg": 60,
            "sodium_mg": 1000,
            "total_carbohydrate_g": 39,
            "dietary_fiber_g": 3,
            "sugars_g": 10,
            "protein_g": 22,
            "calcium_mg": 200,
            "category": "Burgers"
        },
        {
            "name": "Double-Double",
            "serving_size": "1 burger (330g)",
            "serving_size_grams": 330,
            "calories": 670,
            "total_fat_g": 41,
            "saturated_fat_g": 18,
            "trans_fat_g": 1,
            "cholesterol_mg": 120,
            "sodium_mg": 1440,
            "total_carbohydrate_g": 39,
            "dietary_fiber_g": 3,
            "sugars_g": 10,
            "protein_g": 37,
            "calcium_mg": 350,
            "category": "Burgers"
        },
        {
            "name": "French Fries",
            "serving_size": "1 order (125g)",
            "serving_size_grams": 125,
            "calories": 395,
            "total_fat_g": 18,
            "saturated_fat_g": 5,
            "trans_fat_g": 0,
            "cholesterol_mg": 0,
            "sodium_mg": 245,
            "total_carbohydrate_g": 54,
            "dietary_fiber_g": 2,
            "sugars_g": 0,
            "protein_g": 7,
            "potassium_mg": 720,
            "category": "Sides"
        },
        {
            "name": "Vanilla Shake",
            "serving_size": "1 shake (425g)",
            "serving_size_grams": 425,
            "calories": 580,
            "total_fat_g": 31,
            "saturated_fat_g": 19,
            "trans_fat_g": 0,
            "cholesterol_mg": 85,
            "sodium_mg": 350,
            "total_carbohydrate_g": 67,
            "dietary_fiber_g": 0,
            "sugars_g": 62,
            "protein_g": 10,
            "calcium_mg": 350,
            "category": "Beverages"
        }
    ],
    
    "Popeyes": [
        {
            "name": "Chicken Sandwich (Classic)",
            "serving_size": "1 sandwich (260g)",
            "serving_size_grams": 260,
            "calories": 700,
            "total_fat_g": 42,
            "saturated_fat_g": 14,
            "trans_fat_g": 0,
            "cholesterol_mg": 90,
            "sodium_mg": 1443,
            "total_carbohydrate_g": 50,
            "dietary_fiber_g": 2,
            "sugars_g": 8,
            "protein_g": 28,
            "category": "Sandwiches"
        },
        {
            "name": "3pc Signature Chicken (Mild)",
            "serving_size": "3 pieces (340g)",
            "serving_size_grams": 340,
            "calories": 740,
            "total_fat_g": 38,
            "saturated_fat_g": 14,
            "trans_fat_g": 0,
            "cholesterol_mg": 235,
            "sodium_mg": 1765,
            "total_carbohydrate_g": 48,
            "dietary_fiber_g": 3,
            "sugars_g": 0,
            "protein_g": 52,
            "category": "Chicken"
        },
        {
            "name": "Red Beans & Rice (Regular)",
            "serving_size": "1 regular (146g)",
            "serving_size_grams": 146,
            "calories": 230,
            "total_fat_g": 14,
            "saturated_fat_g": 4,
            "trans_fat_g": 0,
            "cholesterol_mg": 10,
            "sodium_mg": 580,
            "total_carbohydrate_g": 23,
            "dietary_fiber_g": 5,
            "sugars_g": 0,
            "protein_g": 7,
            "iron_mg": 1.8,
            "category": "Sides"
        },
        {
            "name": "Cajun Fries (Regular)",
            "serving_size": "1 regular (115g)",
            "serving_size_grams": 115,
            "calories": 270,
            "total_fat_g": 14,
            "saturated_fat_g": 5,
            "trans_fat_g": 0,
            "cholesterol_mg": 5,
            "sodium_mg": 590,
            "total_carbohydrate_g": 33,
            "dietary_fiber_g": 3,
            "sugars_g": 0,
            "protein_g": 4,
            "category": "Sides"
        },
        {
            "name": "Biscuit",
            "serving_size": "1 biscuit (60g)",
            "serving_size_grams": 60,
            "calories": 207,
            "total_fat_g": 10,
            "saturated_fat_g": 5,
            "trans_fat_g": 0,
            "cholesterol_mg": 2,
            "sodium_mg": 525,
            "total_carbohydrate_g": 26,
            "dietary_fiber_g": 1,
            "sugars_g": 2,
            "protein_g": 3,
            "category": "Sides"
        }
    ],
    
    "Shake Shack": [
        {
            "name": "ShackBurger",
            "serving_size": "1 burger (227g)",
            "serving_size_grams": 227,
            "calories": 550,
            "total_fat_g": 33,
            "saturated_fat_g": 15,
            "trans_fat_g": 1,
            "cholesterol_mg": 115,
            "sodium_mg": 1260,
            "total_carbohydrate_g": 26,
            "dietary_fiber_g": 0,
            "sugars_g": 6,
            "protein_g": 35,
            "calcium_mg": 280,
            "iron_mg": 4.5,
            "category": "Burgers"
        },
        {
            "name": "SmokeShack",
            "serving_size": "1 burger (258g)",
            "serving_size_grams": 258,
            "calories": 620,
            "total_fat_g": 37,
            "saturated_fat_g": 16,
            "trans_fat_g": 1,
            "cholesterol_mg": 125,
            "sodium_mg": 1580,
            "total_carbohydrate_g": 27,
            "dietary_fiber_g": 0,
            "sugars_g": 7,
            "protein_g": 39,
            "category": "Burgers"
        },
        {
            "name": "Chicken Shack",
            "serving_size": "1 sandwich (236g)",
            "serving_size_grams": 236,
            "calories": 550,
            "total_fat_g": 31,
            "saturated_fat_g": 7,
            "trans_fat_g": 0,
            "cholesterol_mg": 100,
            "sodium_mg": 1170,
            "total_carbohydrate_g": 34,
            "dietary_fiber_g": 0,
            "sugars_g": 6,
            "protein_g": 33,
            "category": "Chicken"
        },
        {
            "name": "Crinkle Cut Fries",
            "serving_size": "1 regular (158g)",
            "serving_size_grams": 158,
            "calories": 470,
            "total_fat_g": 22,
            "saturated_fat_g": 4.5,
            "trans_fat_g": 0,
            "cholesterol_mg": 0,
            "sodium_mg": 740,
            "total_carbohydrate_g": 63,
            "dietary_fiber_g": 7,
            "sugars_g": 0,
            "protein_g": 6,
            "potassium_mg": 1120,
            "category": "Sides"
        },
        {
            "name": "Vanilla Shake",
            "serving_size": "1 shake (454g)",
            "serving_size_grams": 454,
            "calories": 680,
            "total_fat_g": 39,
            "saturated_fat_g": 24,
            "trans_fat_g": 0,
            "cholesterol_mg": 160,
            "sodium_mg": 330,
            "total_carbohydrate_g": 72,
            "dietary_fiber_g": 0,
            "sugars_g": 69,
            "protein_g": 14,
            "calcium_mg": 560,
            "category": "Shakes"
        }
    ]
}

# Glycemic Index data for common foods
GLYCEMIC_INDEX_DATA = [
    # Grains and Breads
    {"name": "White bread", "glycemic_index": 75, "serving_size_g": 30, "category": "Grains"},
    {"name": "Whole wheat bread", "glycemic_index": 51, "serving_size_g": 30, "category": "Grains"},
    {"name": "Sourdough bread", "glycemic_index": 54, "serving_size_g": 30, "category": "Grains"},
    {"name": "Bagel", "glycemic_index": 72, "serving_size_g": 70, "category": "Grains"},
    {"name": "White rice", "glycemic_index": 73, "serving_size_g": 150, "category": "Grains"},
    {"name": "Brown rice", "glycemic_index": 50, "serving_size_g": 150, "category": "Grains"},
    {"name": "Wild rice", "glycemic_index": 45, "serving_size_g": 150, "category": "Grains"},
    {"name": "Quinoa", "glycemic_index": 53, "serving_size_g": 150, "category": "Grains"},
    {"name": "Oatmeal (instant)", "glycemic_index": 79, "serving_size_g": 250, "category": "Grains"},
    {"name": "Steel-cut oats", "glycemic_index": 55, "serving_size_g": 250, "category": "Grains"},
    {"name": "Corn flakes", "glycemic_index": 81, "serving_size_g": 30, "category": "Cereals"},
    {"name": "All-Bran", "glycemic_index": 38, "serving_size_g": 30, "category": "Cereals"},
    {"name": "Muesli", "glycemic_index": 57, "serving_size_g": 30, "category": "Cereals"},
    
    # Pasta and Noodles
    {"name": "Spaghetti (white)", "glycemic_index": 49, "serving_size_g": 180, "category": "Pasta"},
    {"name": "Spaghetti (whole wheat)", "glycemic_index": 42, "serving_size_g": 180, "category": "Pasta"},
    {"name": "Macaroni", "glycemic_index": 47, "serving_size_g": 180, "category": "Pasta"},
    {"name": "Rice noodles", "glycemic_index": 53, "serving_size_g": 180, "category": "Pasta"},
    {"name": "Udon noodles", "glycemic_index": 55, "serving_size_g": 180, "category": "Pasta"},
    
    # Starchy Vegetables
    {"name": "Baked potato", "glycemic_index": 85, "serving_size_g": 150, "category": "Vegetables"},
    {"name": "Boiled potato", "glycemic_index": 78, "serving_size_g": 150, "category": "Vegetables"},
    {"name": "Sweet potato", "glycemic_index": 54, "serving_size_g": 150, "category": "Vegetables"},
    {"name": "French fries", "glycemic_index": 75, "serving_size_g": 150, "category": "Vegetables"},
    {"name": "Corn", "glycemic_index": 52, "serving_size_g": 150, "category": "Vegetables"},
    {"name": "Peas", "glycemic_index": 48, "serving_size_g": 150, "category": "Vegetables"},
    {"name": "Carrots (cooked)", "glycemic_index": 47, "serving_size_g": 150, "category": "Vegetables"},
    {"name": "Pumpkin", "glycemic_index": 75, "serving_size_g": 150, "category": "Vegetables"},
    
    # Fruits
    {"name": "Apple", "glycemic_index": 36, "serving_size_g": 120, "category": "Fruits"},
    {"name": "Banana (ripe)", "glycemic_index": 51, "serving_size_g": 120, "category": "Fruits"},
    {"name": "Banana (unripe)", "glycemic_index": 30, "serving_size_g": 120, "category": "Fruits"},
    {"name": "Orange", "glycemic_index": 43, "serving_size_g": 120, "category": "Fruits"},
    {"name": "Grapefruit", "glycemic_index": 25, "serving_size_g": 120, "category": "Fruits"},
    {"name": "Grapes", "glycemic_index": 59, "serving_size_g": 120, "category": "Fruits"},
    {"name": "Strawberries", "glycemic_index": 40, "serving_size_g": 120, "category": "Fruits"},
    {"name": "Blueberries", "glycemic_index": 53, "serving_size_g": 120, "category": "Fruits"},
    {"name": "Watermelon", "glycemic_index": 76, "serving_size_g": 120, "category": "Fruits"},
    {"name": "Pineapple", "glycemic_index": 59, "serving_size_g": 120, "category": "Fruits"},
    {"name": "Mango", "glycemic_index": 51, "serving_size_g": 120, "category": "Fruits"},
    {"name": "Peach", "glycemic_index": 42, "serving_size_g": 120, "category": "Fruits"},
    {"name": "Pear", "glycemic_index": 38, "serving_size_g": 120, "category": "Fruits"},
    {"name": "Cherries", "glycemic_index": 22, "serving_size_g": 120, "category": "Fruits"},
    
    # Legumes
    {"name": "Lentils", "glycemic_index": 32, "serving_size_g": 150, "category": "Legumes"},
    {"name": "Chickpeas", "glycemic_index": 28, "serving_size_g": 150, "category": "Legumes"},
    {"name": "Black beans", "glycemic_index": 30, "serving_size_g": 150, "category": "Legumes"},
    {"name": "Kidney beans", "glycemic_index": 24, "serving_size_g": 150, "category": "Legumes"},
    {"name": "Soybeans", "glycemic_index": 16, "serving_size_g": 150, "category": "Legumes"},
    {"name": "Baked beans", "glycemic_index": 48, "serving_size_g": 150, "category": "Legumes"},
    
    # Dairy and Alternatives
    {"name": "Milk (whole)", "glycemic_index": 39, "serving_size_g": 250, "category": "Dairy"},
    {"name": "Milk (skim)", "glycemic_index": 37, "serving_size_g": 250, "category": "Dairy"},
    {"name": "Yogurt (plain)", "glycemic_index": 35, "serving_size_g": 200, "category": "Dairy"},
    {"name": "Yogurt (fruit)", "glycemic_index": 41, "serving_size_g": 200, "category": "Dairy"},
    {"name": "Ice cream", "glycemic_index": 51, "serving_size_g": 50, "category": "Dairy"},
    {"name": "Soy milk", "glycemic_index": 34, "serving_size_g": 250, "category": "Dairy"},
    
    # Snacks and Sweets
    {"name": "Chocolate (dark)", "glycemic_index": 41, "serving_size_g": 50, "category": "Sweets"},
    {"name": "Chocolate (milk)", "glycemic_index": 49, "serving_size_g": 50, "category": "Sweets"},
    {"name": "Honey", "glycemic_index": 61, "serving_size_g": 25, "category": "Sweets"},
    {"name": "Maple syrup", "glycemic_index": 54, "serving_size_g": 25, "category": "Sweets"},
    {"name": "Table sugar", "glycemic_index": 65, "serving_size_g": 10, "category": "Sweets"},
    {"name": "Popcorn", "glycemic_index": 65, "serving_size_g": 20, "category": "Snacks"},
    {"name": "Rice cakes", "glycemic_index": 87, "serving_size_g": 25, "category": "Snacks"},
    {"name": "Pretzels", "glycemic_index": 83, "serving_size_g": 30, "category": "Snacks"},
    {"name": "Potato chips", "glycemic_index": 56, "serving_size_g": 50, "category": "Snacks"},
    
    # Beverages
    {"name": "Orange juice", "glycemic_index": 50, "serving_size_g": 250, "category": "Beverages"},
    {"name": "Apple juice", "glycemic_index": 41, "serving_size_g": 250, "category": "Beverages"},
    {"name": "Cranberry juice", "glycemic_index": 56, "serving_size_g": 250, "category": "Beverages"},
    {"name": "Cola", "glycemic_index": 63, "serving_size_g": 250, "category": "Beverages"},
    {"name": "Sports drink", "glycemic_index": 78, "serving_size_g": 250, "category": "Beverages"},
    
    # Fast Food Items
    {"name": "Pizza", "glycemic_index": 60, "serving_size_g": 100, "category": "Fast Food"},
    {"name": "Hamburger bun", "glycemic_index": 61, "serving_size_g": 50, "category": "Fast Food"},
    {"name": "Taco shell", "glycemic_index": 68, "serving_size_g": 20, "category": "Fast Food"},
    {"name": "Donut", "glycemic_index": 76, "serving_size_g": 60, "category": "Fast Food"},
]